### ISSUE TITLE
Einsatzverwaltung fehlt im Dashboard

### ISSUE THREAD

**Issue by Schmakus** [abrain/einsatzverwaltung#100]
Hi,
seit dem update auf 1.0.0 ist der Menüpunkt zum Erstellen von Berichten, Anlegen von Fahrzeugen, etc. im Dashboard verschwunden!
![wp_dashboard](https://cloud.githubusercontent.com/assets/8231359/10633976/c9805a4a-77ee-11e5-8c34-46270ff5d003.PNG)

**Comment by abrain** [comment]
Dieses Problem tritt bei ein paar wenigen Nutzern nach einem Update auf, die Umstände sind aber alles andere als klar. Ich habe auch von keinem Nutzer zweimal gehört. Vielleicht bekommen wir ja zusammen Licht ins Dunkel.
Klar ist bisher nur, dass es etwas mit den Nutzerrechten zu tun hat. Soweit ich das mitbekommen habe, hat Herumspielen an den entsprechenden Einstellungen unter Einstellungen > Einsatzverwaltung das Problem beseitigt.
Vielleicht einfach einmal versuchen, Rollen einzeln dazuzunehmen oder abzuwählen und dann noch einmal sehen, ob der Menüpunkt auftaucht.

**Comment by abrain** [comment]
Es wäre natürlich auch interessant, wie die Rechte im Moment aussehen. Das lässt dann eventuell auch schon Rückschlüsse auf die Ursache oder die Lösung zu.
Dazu bräuchte ich Informationen zu einem bestimmten Eintrag in der Datenbank, wenn das möglich ist.

**Comment by Schmakus** [comment]
Hi, also das mit den Rollen funktioniert nicht.
Hab alles Mögliche versucht.
Welche Infos aus der Datenbank brauchst du?

**Comment by abrain** [comment]
Ich bräuchte bitte aus der Tabelle `wp_options` den Inhalt des Eintrags `wp_user_roles`, dort ist gespeichert, welche Benutzerrolle, welche Rechte hat. Wenn du das nicht hier postet möchtest, auch gerne per Mail an kontakt@abrain.de

**Comment by Schmakus** [comment]
Hi, habe dir per mail geschickt.
Wenn ich mich als "Redakteur" anmelde, hab ich Zugriff auf die Einsatzverwaltung.
Als Admin nicht.

**Comment by abrain** [comment]
Habe ich erhalten, danke. Frage: Hattest du mal ein Plugin wie [User Role Editor](https://wordpress.org/plugins/user-role-editor/) installiert?

**Comment by Schmakus** [comment]
Kann ich leider nicht genau sagen! :-)

**Comment by abrain** [comment]
Die Rolle "Administrator" hat die nötigen Rechte, es scheint aber bei der Auswertung der Rechte irgendetwas schiefzulaufen. Leider gibt es bei WordPress mehr als einen Weg, Benutzerrechte zu vergeben, entsprechend gibt es keine Musterlösung. Ich werde einen der anderen Wege ausprobieren, der ohnehin eine flexiblere Rechtevergabe ermöglicht.

**Comment by Schmakus** [comment]
Ok, wann wird das neue Update veröffentlicht?

**Comment by abrain** [comment]
Bin gerade dabei, das umzuschreiben. Je weiter ich mich in WordPress hineingrabe, desto weniger verstehe ich, wie es nicht funktionieren kann. Und nachdem das Problem so selten auftritt, kann es fast nicht an WordPress selbst liegen. Welche Version von WP benutzt denn?

**Comment by Schmakus** [comment]
Ich verwende die aktuellste (nicht beta) Version von WordPress.

**Comment by abrain** [comment]
Ok, danke. Könntest du bitte mal die anderen Plugins durchgehen, eines nach dem anderen deaktivieren und immer wieder prüfen, ob der Menüpunkt noch verschwunden ist?

**Comment by Schmakus** [comment]
Hi,
das deaktivieren/aktivieren aller Plugins (einzeln, komplett,...) brachte keine Abhilfe.

**Comment by abrain** [comment]
Danke für's Ausprobieren. Ok, dann muss ich wohl doch ran.

**Comment by abrain** [comment]
So, ein erster Versuch. BItte mal [diese Version](https://github.com/abrain/einsatzverwaltung/blob/hotfix/1.0.1/src/einsatzverwaltung-core.php) der einsatzverwaltung-core.php verwenden.

**Comment by Schmakus** [comment]
leider keine Änderung!

**Comment by abrain** [comment]
Ah, sehr gut. Ist zwar komisch, dass es dann nicht gleich ging, aber gut, mir soll's recht sein ;)

**Comment by abrain** [comment]
Na wunderbar, der Fehler tritt immer noch auf, und wie gewohnt äußerst vereinzelt. Ebenso besteht noch die merkwürdige Eigenart, dass ein neu erstellter Administratoraccount wiederum berechtigt ist. Das heißt, da gibt es nochmal einen neuen Anlauf.
