### ISSUE TITLE
Kompatibilität zu NextScripts: Social Networks Auto-Poster

### ISSUE THREAD

**Issue by Stephan-90** [abrain/einsatzverwaltung#102]
Derzeit erstelle ich eine Webseite für unsere Feuerwehr mit Wordpress. Und um die Einsätze zu Dokumentieren ist dieses Plugin einfach Wundervoll. Nun wollen wir gerne die Einsätze, auch auf Facebook teilen. Dafür habe ich mir wie im Titel schon genannt "NextScripts: Social Networks Auto-Poster" heruntergeladen.
Allerdings passiert beim teilen etwas das ich nicht ganz nachvollziehen kann. Und zwar werden die Standard Einträge wie Mannschaftsstärke, Einsatzleiter, Ort, Datum, usw bei einer automatischen Veröffentlichung zwar als Titel angezeigt, allerdings besitzen diese keinen Wert, stehen also als leer da. Wenn ich allerdings Externe Einsatzmittel, Fahrzeuge, Einsatzart und Alamierungsart auswähle, werden diese richtig angezeigt, aber wirklich nur diese. Die anderen Werte bleiben immer leer.

Jetzt kann ich allerdings nicht sagen, ob es an deinem oder an dem NextScripts Plugin liegt. Ich habe mich intensiv damit beschäftigt den Fehler zu finden, aber bin leider nicht dahintergekommen. Deshalb hoffe ich, das du vll eine Lösung finden kannst.

**Comment by abrain** [comment]
Ich nehme an, das passiert nur beim automatischen Teilen und klappt aber wie vorgesehen, wenn der Bericht manuell geteilt wird?

Wenn ja, dann liegt das höchstwahrscheinlich daran, dass der Einsatzbericht in zwei Schritten gespeichert wird. Zuerst speichert WordPress den ganzen Kram, der bekannt ist (also Standarddinge wie Überschrift, Beitragstext und die ganzen registrierten Taxonomien wie Fahrzeuge etc.) und gibt dann dem Plugin Bescheid, dass ein Beitrag gespeichert wurde. Daraufhin hängt dann das Plugin die zusätzlichen Angaben wie Mannschaftsstärke, Ort, etc. an den Beitrag an.

WordPress benachrichtigt aber natürlich nicht nur die Einsatzverwaltung über das Speichern eines Beitrags, sondern jedes Plugin, das sich dafür interessiert. Ohne genau die Funktionsweise von NextScripts nachvollzogen zu haben, habe ich gesehen, dass es sich auch für dieses Event registriert hat. Es ist also sehr gut möglich, dass der Beitrag an die sozialen Netzwerke geschickt wird, bevor die zusätzlichen Daten an den Einsatzbericht angehängt wurden.

So wie es aussieht kann ich diese Aufteilung in zwei Schritte doch weiter zusammenfassen und alles oder fast alles auf einmal speichern. Bis das aber geändert ist, würde ich vorschlagen den Beitrag erst zu speichern und dann zu veröffentlichen.

**Comment by Stephan-90** [comment]
Danke schonmal für die schnelle Antwort. Ich hab es gerade einmal getestet und wie du sagst ist es beim automatischen speichern so, das diese Informationen fehlen.
Wenn ich den Beitrag im nachhinein nocheinmal poste, dann stehen zwar unter dem shortcode %FULLTEXT% keine Werte, also in diesem Fall wirklich nichts, noch nicht einmal die Titel wie Einsatzleiter, Ort usw. Aber im angehängten Post, wird alles angezeigt, was beim automatischen teilen nicht der Fall war.
Also wird es wohl so sein wie du es beschreibst.
Ich werde dementsprechend dann ersteinmal entweder danach posten, oder beim automatischen post, selbst etwas dazu schreiben.

**Comment by Schmakus** [comment]
Hi,
bei mir wurde vor kurzem nur der eigentliche Beitrag, ohne Einsatzdaten, via Next Script auf Facebook gepostet.
Seit den letzten 2-3 Updates der Einsatzverwaltung werden nun auch die Einsatdaten vorangestellt.
Auch hier teilweise ohne Inhalt.

**Comment by abrain** [comment]
Hallo, hat sich hier in letzter Zeit etwas verändert? Bei NextScripts stand mal im Changelog 

> Improvement - Better support for Custom Post types. 

aber, ich habe im Quelltext nichts gesehen, was ich mit dem hier beschriebenen Problem in Verbindung bringen würde.

In [diesem Support-Thread](https://wordpress.org/support/topic/inserting-custom-post-type-field?replies=9) empfehlen die Pluginautoren für diesen Fall eine Zeitverzögerung beim Posten einzustellen.

**Comment by abrain** [comment]
@Stephan-90 @Schmakus Habt ihr die vorhergehende Antwort gesehen?

**Comment by Stephan-90** [comment]
Ja, ich das habe ich gelsen. Bin nur leider noch nicht dazu gekommen es zu testen. Aber sobald ich Informationen darüber habe, melde ich mich nocheinmal.
