### ISSUE TITLE
"verschobene Tabelle" bei "Besonderen Einsätzen"

### ISSUE THREAD

**Issue by SMundt** [abrain/einsatzverwaltung#104]
Hallo,

auf das neue Feature "Besonderer Einsatz" habe ich lange gewartet und es natürlich auf meiner Seite gleich umgesetzt.
Wenn ich allerdings folgenden Shortcode nutze:

[einsatzliste jahr=* monatetrennen=nein sort=ab options=special]

dann verschiebt sich die gesamte Tabelle irgendwie:

![screen](https://cloud.githubusercontent.com/assets/12255583/14055295/15f9c376-f2e1-11e5-88ba-5374670edee8.png)

Auf dem Handy ist die Darstellung OK, nur im Browser auf dem PC leider nicht.

Irgend eine Idee, woran das liegt?

**Comment by abrain** [comment]
Das liegt daran, dass für jedes Jahr eine neue Tabelle begonnen wird und der Browser die Spaltenbreite nach dem jeweiligen Inhalt berechnet. Dieses Problem kann man entweder durch feste Spaltenbreiten beheben oder indem man alles in eine einzige, lange Tabelle packt. Beide Varianten gab es zeitweise im Plugin, aber beide sind irgendwie unschön.

Wenn genug Einsatzberichte pro Tabelle vorhanden sind, dürfte am Schluss jede Tabelle in etwa die gleichen Spaltenbreiten haben. Andererseits kommt es auch nicht oft vor, dass man mehrere dieser Tabellen untereinander anzeigt.

Für diesen Fall allerdings kann ich mir gut eine weitere `option` für den Shortcode vorstellen, der dafür sorgt, dass ausnahmsweise nicht für jedes Jahr eine neue Tabelle mit eigener Überschrift begonnen wird. Bei dieser Anzahl von Zeilen kann man das ruhig in einer einzigen Tabelle anzeigen.

P.S.: `monatetrennen=nein` und `sort=ab` kannst du dir theoretisch sparen, das sind die Standardeinstellungen

**Comment by SMundt** [comment]
OK, dann ist dieses Verhalten ja "normal".

Das in eine option zu verpacken wäre natürlich absolute Oberklasse...
