### ISSUE TITLE
Einsatzleiter nicht veröffentlichen

### ISSUE THREAD

**Issue by eret12** [abrain/einsatzverwaltung#105]
Hallo,

wir fänden die Option schön, dass der Einsatzleiter zwar hinterlegt werden kann, diese Daten aber nicht veröffentlicht werden.
So hätte man bei Rückfragen noch einen Ansprechpartner (Einsatzleiter) intern hinterlegt.
Aus Datenschutz möchten wir hier allerdings keine Namen veröffentlichen.
Ebenso wäre es super, wenn intern hinterlegt werden kann, wer die Bilder des Einsatzes erstellt hat.
Hier wäre also ein zusätzliches Feld „Fotograf“ wünschenswert, das ebenfalls optional nicht veröffentlicht wird.

Lg Andre

**Comment by abrain** [comment]
Mit #155 wurde eine Möglichkeit geschaffen, das Layout der Einsatzberichte selbst zu bestimmen. Dadurch kann beispielsweise das Feld "Einsatzleiter" bewusst ausgespart werden.
