### ISSUE TITLE
Einsatznummer ohne Jahreszahl

### ISSUE THREAD

**Issue by eret12** [abrain/einsatzverwaltung#106]
Hallo,

die Einsatznummer mir vorgehängter/angehängter Jahreszahl finde ich persönlich zu lang.
Wäre es hier nicht möglich die Einsatznummer ohne eine Jahreszahl anzeigen zu lassen?
Also als laufende Nummer wie es auch bei den Übersichtstabellen möglich ist?
Es wäre dafür ja nur nötig das Jahr auszufiltern.

Lg Andre

**Comment by abrain** [comment]
Die laufende Nummer ist auch verfügbar, wird bisher aber nur in der Übersicht angezeigt. Mit Version 1.2.2 gibt es die laufende Nummer auch als ersetzbaren Tag für das formatierbare Widget.

Hier geht es speziell um die Anzeige der einzelnen Einsatzberichte?

**Comment by eret12** [comment]
Hallo,

ja genau hier geht es lediglich um die Anzeige der Einsatzberichte.

Lg Andre

**Comment by abrain** [comment]
Die Einsatzberichte selbst haben leider in all der Zeit bisher keine Überarbeitung erfahren, das sehe ich auch noch als Problem. Da müssen definitiv mehr Einstellungsmöglichkeiten her. Eine Überlegung ist, das Prinzip des Widgets mit eigenem Format zu übernehmen und den Benutzer eine Vorlage mit Platzhaltern erstellen zu lassen.
Das ist aber eher was für Fortgeschrittene, also kann das nur eine Option zusätzlich zu einer vorgegebenen Variante sein. Hier dreht sich die Geschichte aber wieder im Kreis, weil die vorgegebene Variate trotzdem noch einstellbar sein soll ;) Also ich bin mir da selbst nicht ganz sicher, was das klügste ist.

**Comment by abrain** [comment]
Seit Version 1.4.0 können Einsatzberichte mit Templates formatiert werden, wodurch auch die laufende Nummer angezeigt werden kann.
