### ISSUE TITLE
Rechtesystem ausbauen

### ISSUE THREAD

**Issue by eret12** [abrain/einsatzverwaltung#108]
Hallo,

ist es möglich, dass Rechtesystem noch weiter auszubauen?
Ich würde gerne einigen Usern erlauben Einsatzberichte anzulegen in vollem Umfang. Lediglich das Veröffentlichen sollte blockiert sein, so dass die Einsatzberichte erst in Revision gehen und von befugten Benutzern freigegeben werden müssen.
Da Rechtesystem von WordPress ist so ja standartmäßig aufgebaut.
Wäre es möglich dies auch bei dem Plugin einzufügen?

Lg Andre

**Comment by abrain** [comment]
Das Rechtesystem hatte ich schon für Version 1.3.0 ins Auge gefasst. Wenn nicht noch etwas anderes dazwischenkommt, wird das so passieren.

**Comment by eret12** [comment]
Hallo,

super!

Lg Andre

**Comment by abrain** [comment]
Wenn man's genau nimmt, ist das übrigens schon umgesetzt, es fehlt nur die Oberfläche, um detaillierte Einstellungen machen zu können. Für die Einsatzberichte sind aber bereits diese verschiedenen Berechtigungen vorhanden. Das heißt, die Berechtigungen könnten übergangsweise mit einem der Benutzerrechte-Plugins vergeben werden.

**Comment by eret12** [comment]
Hallo,

diese Meldung werde ich nun schließen.
Mit dem Plugin „User Role Editor“ können die Berechtigungen optimal eingestellt werden.
Da wir das Plugin ohnehin schon für andere Berechtigungsverwaltungen verwenden, ist diese Lösung für uns optimal.

Lg Andre
