### ISSUE TITLE
Fahrzeuge externen Link zuweisen

### ISSUE THREAD

**Issue by eret12** [abrain/einsatzverwaltung#109]
Hallo,

da wir alle Fahrzeuge aufführen, also auch die von externen Feuerwehren, wäre es schön, wenn den Fahrzeugen auch alternativ ein externer Link zugewiesen werden kann. Wir würden bei externen Fahrzeugen gerne direkt auf die Fahrzeugseite der anderen Feuerwehr verweisen.

Lg Andre

**Comment by abrain** [comment]
Die Trennung in eigene Fahrzeuge und externe Einsatzmittel ist auch aus anderen Gründen überarbeitungsbedürftig. Diese Anforderung kann ich gerne mit einfließen lassen.

**Comment by Rene-Auberger** [comment]
Dieser Issue ist zwar schon fast 4 Jahre alt aber ich hole ihn doch nochmal hoch. Ich würde das Feature auch gern sehen. Wir haben alle Fahrzeuge auf einer Seite und ich müsste Links mit auf die Seite inkl Anchor setzen, damit man direkt beim richtigen Fahrzeug landet. Das ließe sich über die gleiche Funktion machen wie die externen Seiten zu verlinken, nämlich in dem man den Link selbst in einem Textfeld eintragen kann.

**Comment by abrain** [comment]
Ist eingebaut, kommt mit dem nächsten Update.
