### ISSUE TITLE
Fahrzeuge erscheinen in Breadcrump

### ISSUE THREAD

**Issue by eret12** [abrain/einsatzverwaltung#110]
Hallo,

wenn ich auf die Seite eines Einsatzberichtes gehe, so erscheint in den Breadcrumps von WordPress folgendes:
Startseite » Einsatzberichte » Talheim » LF 8/6 » Einsatzbericht Feuerwehr Talheim: 02. Einsatz 2015

Die Daten „Talheim“ und „LF 8/6“ werden aus den ausgewählten Fahrzeugen bezogen. Das sollte ja allerdings nicht sein.
Wäre es möglich anstatt den zwei genannten Daten z.B. „Einsätze 2015“ anzeigen zu lassen?
Also dass das Jahr der Einsätze mit aufgenommen wird?

Link zum Problem:
http://www.feuerwehr-talheim.de/einsatzberichte/2015002/

Lg Andre

**Comment by abrain** [comment]
Das ist eine Spezialität des Themes customizr.

> Since 3.1.20, displays all levels of any hierarchical taxinomies by default and for all types of post (including hierarchical CPT). This feature can be disabled with a the filter : tc_display_taxonomies_in_breadcrumb (set to true by default). In the case of hierarchical post types (like page or hierarchical CPT), the taxonomy trail is only displayed for the higher parent.

Müsste mit einem Filter der Art
```php
add_filter('tc_display_taxonomies_in_breadcrumb', function ($display_taxonomies, $post_type) {
    return ('einsatz' === $post_type ? false : $display_taxonomies);
}, 10, 2);
```
klappen, dass nur bei den Einsatzberichten diese Funktion ausgeschalten wird.

**Comment by eret12** [comment]
Perfekt, jetzt stimmt es.
