### ISSUE TITLE
Mehrere Einsätze zusammenfassen

### ISSUE THREAD

**Issue by heikobornholdt** [abrain/einsatzverwaltung#116]
Bei unser bisherigen Einsatzdatenbank (Eigenentwicklung) hatten wir die Möglichkeit, mehrere Einsätze in einem Eintrag zusammenzufassen. Das war z.B. ganz nützlich, wenn wir z.B: aufgrund eines Unwetters diverse ähnliche Einsätze hatten hatten.

Im Eingabeformular war es dann einfach möglich, mehrere Einsatznummern zu hinterlegen.

Ich würde mich freuen, wenn so eine Funktion auch in diesem Plugin Einzug erhalten würde.

Hier ein Beispiel, wie das auf unserer Webseite dann ausgegeben wurde: https://www.feuerwehr-pinneberg.de/eins%C3%A4tze/2007/1417-containerbraende-rauchentwicklungen-gesamtes-stadtgebiet/

**Comment by abrain** [comment]
Sowas ähnliches hatte ich mit #80 angedacht, der Hintergrund war der selbe: Mehrere Unwettereinsätze hintereinander und auch parallel.

Meine bisherige Vorstellung dieser Funktion war: Die Einsatzberichte werden einzeln geschrieben, im Nachhinein können jedoch mehrere Berichte ausgewählt werden, die zu einem (ich nenne es mal) Metaeinsatz zusammengefasst werden. Das ermöglicht dann eine andere Darstellung in der Tabelle (z.B. als einzelner Einsatz, aufklappbar) oder auch in der Einzelansicht ("Dieser Einsatz gehört zu einer Serie von X Einsätzen").

Den Ansatz, einen Einsatzbericht für alles anzulegen und diesen für X Einsätze zählen zu lassen, finde ich auch durchaus charmant. So genau lässt sich Anfang und Ende eines Einsatzes in diesen Nächten vielleicht gar nicht beziffern oder es ist nicht relevant. Wer trotzdem alles genau haben will, kann weiterhin einzelne Einsatzberichte eintragen.

**Comment by heikobornholdt** [comment]
Wir hatten folgende Motivation für dieses Feature bei unserer Einsatzdatenbank:
Wir wollten die Arbeit für das dokumentieren der Einsätze verringern. Anstelle, dass n mal über einen abgeknickten Baum geschrieben werden muss, wird einfach in das Feld "Einsatznummer" ein Wertebereich (z.B. 104-108) eingetragen. Alles andere bleibt wie vorher.
Das Wichtigste war für uns - neben der Arbeitserleichterung - die korrekte Berechnung der Menge von Einsätzen.
Technisch hatten wir zwei MySQL-Tabellen: eine für die Einsätze und eine für die Nummern.
