### ISSUE TITLE
Einsatznummern beim Import übernehmen

### ISSUE THREAD

**Issue by heikobornholdt** [abrain/einsatzverwaltung#117]
Im Moment ist es nicht möglich, beim Importieren von Einsatzberichten die Nummer zu übernehmen.

Das Feld steht leider nicht zur Auswahl:
<img width="331" alt="screen shot 2017-01-08 at 00 52 45" src="https://cloud.githubusercontent.com/assets/789788/21746169/d437527a-d53c-11e6-83b8-bc68d228e048.png">

Bitte ergänzen

**Comment by abrain** [comment]
Das liegt daran, dass die Einsatznummer im Moment eindeutig sein muss. Das sollte sie natürlich immer sein, aber in diesem Fall wird sie innerhalb von WordPress als eindeutige Referenz für jeden Einsatzbericht verwendet. Das soll sich mit Version 1.3 ändern, daher wäre auch der Import von Einsatznummern nicht mehr problematisch.

**Comment by abrain** [comment]
Mit 7e988c7a1c9d6e816a085f410dc3f5db5bc64744 können Einsatznummern importiert werden, sofern die automatische Verwaltung der Einsatznummern deaktiviert ist.

**Comment by heikobornholdt** [comment]
Danke dir, funktioniert 👍
