### ISSUE TITLE
Vergangene Einsätze als Tabelle anzeigen

### ISSUE THREAD

**Issue by saschabreipohl** [abrain/einsatzverwaltung#120]
Wie schon auf der Homepage der Einsatzverwaltung erwähnt, wäre es gut die Einsätze der vergangenen Jahre in Tabellenform anzeigen lassen zu können. 

Es wäre natürlich noch besser, wenn man diese Funktion fest einbauen würde. Also in der Jahresübersicht zu der Seite mit der `[einsatzliste]` verlinken mit dem Zusatz /?jahr=20xx und dies im Shortcode auswerten oder so ähnlich.

Oder bitte zumindest den Blogpost veröffentlichen der die Änderung der Archivseite im Child-Theme erläutert. Damit braucht man das Rad nicht neu erfinden.

**Comment by abrain** [comment]
Hab's endlich geschafft, den Blogpost zu schreiben: https://einsatzverwaltung.abrain.de/2017/12/das-jahresarchiv-als-tabelle-darstellen/
