### ISSUE TITLE
Shortcode für Einsatz-Zählung hinzufügen

### ISSUE THREAD

**Issue by Revyn112** [abrain/einsatzverwaltung#121]
Hallo,

es wäre super wenn ein Shortcodes zum Zählen von div. Einsatzarten / gesamten Einsätzen hinzugefügt werden kann mit diversen Parametern:

- Zeitraum: Alle / Jahr / Monat+Jahr
- Einsatzarten: Alle / Kategorie (Alles Childs eines Parents) / Einzelne Einsatzart
- Fahrzeuge: Alle / Einzelne

Eine Mögliches Format für den Shortcode:

[einsaetze jahr=\* art=\* fahrzeug=\*]
[einsaetze jahr=2016 art=37 fahrzeug=*] //art ist die Tag-ID der Einsatzart und Fahrzeug die Fahrzeug-ID

Die Ausgabe ist dann einfach der Wert der Einsätze.

Gruß
Revyn112

**Comment by abrain** [comment]
Kommt mit Version 1.6.0
