### ISSUE TITLE
Einsatzberichte wieder über Einsatznummer erreichbar machen

### ISSUE THREAD

**Issue by abrain** [abrain/einsatzverwaltung#126]
Seit Version 1.3.0 werden die Links zu den Einsatzberichten nicht mehr aus den Einsatznummern generiert, sondern wie sonst bei WordPress üblich aus dem Titel des Berichts. Dadurch hat eine Feuerwehr nun das Problem bekommen, dass nicht mehr durch das Aufrufen einer URL festgestellt werden kann, ob ein Einsatzbericht zu einer bestimmten Einsatznummer vorhanden ist.

Analog zu `/einsatzberichte/titel-des-berichts/` wäre ein mögliches URL-Schema `/einsatznummern/2017123/` denkbar.

**Comment by sebastianroming** [comment]
Eventuell wäre auch `/einsatzberichte/2017123/titel-des-berichts/` denkbar?

**Comment by abrain** [comment]
Das hatten wir ja in https://github.com/abrain/einsatzverwaltung/issues/94#issuecomment-101353484 schon mal angesprochen, was aber eher ästhetische und SEO-Gründe hatte. Diese URL hier sollte so eigentlich gar nirgendwo auftauchen, sondern nur die alte Funktionalität wieder nutzbar machen.

Die Einsatznummer in die URL zu legen ist mittlerweile gar nicht mehr so einfach, weli in dem Freitextfeld alles mögliche stehen könnte, was in einer URL nicht stehen sollte. Es sollte gut möglich sein das Jahr und den Monat mit in die URL zu bringen (vgl. Permalinks für normale Beiträge), aber das sollten wir in einem eigenen Issue behandeln.

**Comment by denis1994** [comment]
Bei uns haben die Einsätze oft den gleichen Titel, weil wir die Einsatzstichwörter benutzen (z.B. Vehrkehrsunfall, Hilfeleistung Rettungsdienst, usw). Durch die Umstellung der Links, haben jetzt viele Berichte den gleichen Link und unterscheiden sich nur noch eine Zahl zum Schluss. Da wäre wie ein Format wie sebastianroming vorgeschlagen hat besser.
