### ISSUE TITLE
Widget "Letzte Einsätze" - Einsätze mit Fotos entsprechend anzeigen

### ISSUE THREAD

**Issue by denis1994** [abrain/einsatzverwaltung#127]
Man kann ja bei Einsätzen ein Haken setzen wenn es Fotos im Einsatzbericht gibt. In der Liste in der Einsätze kann man auch entsprechend eine Spalte anzeigen lassen. Aber im Widget "Letzte Einsätze" fehlt das leider.

**Comment by abrain** [comment]
Oh, das stimmt. Danke!
