### ISSUE TITLE
Beim Schreiben von Einsatzberichten nur aktuelle Fahrzeuge anzeigen

### ISSUE THREAD

**Issue by abrain** [abrain/einsatzverwaltung#131]
Nachdem immer wieder Fahrzeuge ausgemustert und ersetzt werden, wächst die Liste mit verfügbaren Fahrzeugen immer weiter. Um die Übersicht zu behalten, sollen Fahrzeuge als ausgemustert markiert werden können und entsprechend bei neuen Einsätzen nicht mehr zur Auswahl angeboten werden. Beim Bearbeiten oder nachträglichen Anlegen von Einsatzberichten für diese Fahrzeuge sollen sie jedoch weiterhin ausgewählt werden können.

Es gilt herauszufinden, inwiefern die häufig genutzten Fahrzeuge gefiltert werden können, ohne die Auflistung von allen Fahrzeugen zu beeinflussen.

Alternativ könnte die Liste nicht gefiltert und ausgemusterte Fahrzeuge ausgegraut werden.

![bildschirmfoto 2017-06-12 um 12 50 56](https://user-images.githubusercontent.com/1263052/27030776-d0d750c0-4f6d-11e7-9631-84cbe852f61a.png)

**Comment by heikobornholdt** [comment]
Wir laufen bei unserer Wehr auch in das gleiche Problem (Aktuell 30 Fahrzeuge im System; 10 davon ausgemustert).

Eventuell könnte man auch die ausgemusterten Fahrzeuge einfach nach unten sortieren.

**Comment by sebastianroming** [comment]
Klugscheißer-Modus: Ein Fahrzeug kann nicht nur ausgemustert werden, sondern auch in andere Einsatzabteilungen etc. verschoben werden - also ändert sich der Funkrufname (1/47 => 2/47). Wenn man das Ganze nun auf die Spitze treiben will, könnte man sich auch mit einer Historie befassen, damit Funkrufnamen in den Einsatzberichten korrekt bleiben.

:see_no_evil:

**Comment by heikobornholdt** [comment]
Ähnliches Problem besteht bei uns auch bei den Einsatzarten. Wir haben bei uns Einsätze der letzten 15 Jahre in der Datenbank und ein Haufen alter Einsatzarten, die es heute nicht mehr gibt.

**Comment by abrain** [comment]
Danke @sebastianroming und @heikobornholdt, das sind beides valide Probleme. Könnt ihr bitte dafür eigene Issues aufmachen?

**Comment by sebastianroming** [comment]
@abrain Erledigt :+1:
