### ISSUE TITLE
Ausgeben von mehreren Einsätzen auf einer Sliderseite

### ISSUE THREAD

**Issue by thesgt** [abrain/einsatzverwaltung#134]
Moin Moin,
da ich ein absoluter Anfänger bin, was die Programmierung von Wordpress angeht, eine sehr grundlegende Frage:
Wie rufe ich Funktionen auf, spezieller wenn ich zB. die letzten 3 Einsätze ausgeben will ? Mein erster Gedanke ging so in die Richtung Aufruf vom Shortcode, damit ich immer die aktuellsten 3 Einsätze habe.
`<?php `
`	$shortcode = array('limit'=>'3','options'=>'noHeading');`
`		if(function_exists("einsatzliste")){`
`			echo einsatzliste($shortcode );`
`		}else{`
`			echo "Fehler bei der Ausgabe!";`
`		}?>`
Evt. jemand eine Idee ?

Grüße

**Comment by abrain** [comment]
Hi,
wenn du Funktionen des Plugins mitbenutzen möchtest, bist du am Besten beraten, auf die Shortcodes zurückzugreifen. Natürlich könntest du auch direkt die entsprechenden Klassen ansprechen, aber da diese nicht als API gedacht sind, könnte sich da jederzeit unangekündigt etwas ändern.

Um einen Shortcode auszuführen kannst du [do_shortcode](https://developer.wordpress.org/reference/functions/do_shortcode/) verwenden, z.B.:

`
do_shortcode('[einsatzliste limit="3" options="noHeading"]');
`

**Comment by abrain** [comment]
Aber noch eine andere Frage: Im Titel erwähnst du eine Sliderseite. Was meinst du damit? Dass die neuesten X Einsatzberichte in einem Slider dargestellt werden?

**Comment by thesgt** [comment]
Moin,
Danke für deine Antwort , ich werde das ganze mal heute oder morgen Abend ausprobieren.

Nicht ganz.. damit ist eine einzelne Sliderseite auf der Fontoage gemeint, welche ein Art Feed der letzten 3-5 Einsätze enthalten soll, je nach dem wie es ausschaut.

**Comment by thesgt** [comment]
Funktioniert gut, nur sieht es nicht ganz so toll aus ^^

![tabelle](https://user-images.githubusercontent.com/20864772/27469346-59276f94-57ef-11e7-92e8-54b3dceae5ed.png)

gibt es eine Möglichkeit das ganze anzupassen oder gar nur ein Array zurückzubekommen anstelle einer fertigen Tabelle ? Oder müsste man dann wieder auf Funktionen zugreifen, welche nicht als API gedacht sind ?

**Comment by abrain** [comment]
Da gibt es jetzt drei Möglichkeiten:

### Variante 1
Du passt das CSS der Tabelle an, damit nicht mehr der Hintergrund durchscheint. Das wäre die minimalinvasive Lösung und auch die am zukunftssichersten (die CSS-Klassen ändern sich in der Regel nicht)

### Variante 2
Die Einsatzberichte kannst du selbst abrufen, mit der Klasse `abrain\Einsatzverwaltung\ReportQuery`.

```php
$query = new ReportQuery();
$query->setLimit(3);
$query->setOrderAsc(false); // der neueste Einsatz zuerst, ansonsten die Zeile einfach rauswerfen
$reports = $query->getReports();
```
Du erhältst ein Array mit Objekten vom Typ `abrain\Einsatzverwaltung\Model\IncidentReport`, von denen du die Details zu den Einsätzen abfragen kannst. Das ist aber vielleicht etwas mühselig zu formatieren, besser ist da:

### Variante 3
Es gibt bei den Widgets ja bereits die Möglichkeit den Content selbst zu gestalten. Dabei füllt man seinen HTML-Code mit Platzhaltern auf, in die dann die Daten der Einsatzberichte eingefügt werden. Das könntest du auch manuell anstoßen, die Klasse dafür ist `abrain\Einsatzverwaltung\Util\Formatter`. Du rufst wie in Variante 2 die Einsatzberichte ab, und rufst für jeden Bericht folgendes auf:
```php
$formatter->formatIncidentData( $pattern, array(), $report->getPostId() );
```
`$pattern` ist dein HTML mit Platzhaltern, ein Beispiel und die möglichen Platzhalter siehst du [hier](https://einsatzverwaltung.abrain.de/wp-content/uploads/2016/03/widget-format-einstellungen.png) (auf dem Bild fehlt noch `%seqNum%` für die laufende Nummer). Zurück bekommst du `$pattern` mit ersetzten Platzhaltern.

Bei Variante 2 und 3 kann ich nicht garantieren, dass es auf ewig so bleibt. Derzeit sehe ich aber keinen Anlass diese beiden Aufrufe zu ändern bzw. ändern zu müssen.
