### ISSUE TITLE
Einsatzarten archivierbar/sortierbar machen

### ISSUE THREAD

**Issue by heikobornholdt** [abrain/einsatzverwaltung#135]
**Problem:**
Wie bereits in https://github.com/abrain/einsatzverwaltung/issues/131#issuecomment-308480832 angesprochen befinden sich in unserer Einsatzdatenbank die Einsätze der letzten 15 Jahre. Dadurch haben wir aktuell 165 verschiedene Einsatzarten in der Datenbank.

Die große Menge an Einsatzarten kommt daher, dass in Schleswig-Holstein in der Vergangenheit (mehrmals?) der Katalog an Einsatzstichworten überarbeitet wurde.

Das heißt also, dass viel der Einsatzarten bei neuen Einsatzarten gar keine Verwendung mehr finden und es daher eher störend ist, dass diese mit im Dropdown-Feld bei der Eingabe von Einsätzen erscheint.

---
**Lösungsvorschlag:**
Es wäre schön, wenn man Einsatzarten daher archivierbar/sortierbar machen könnte.

Ich kenne mich mit den Taxonomien in WordPress nicht aus, aber kann man nicht vielleicht ein boolesches Attribut "Archiviert" ergänzen und die archivierten Einsatzartzen dann am Ende vom Dropdown aufzulisten?

**Comment by heikobornholdt** [comment]
@abrain Hast du einen Vorschlag, wie das Feature umgesetzt werden soll? Ich könnte mich dann um die Implementierung kümmern.

**Comment by abrain** [comment]
Danke dir! Die Werte der Taxonomien haben mittlerweile wie die Beiträge auch Metainformationen (`termmeta`). Dort ein boolsches Attribut anzuhängen ist kein Problem. Bei den Fahrzeugen und externen Einsatzmitteln mache ich das auch schon (siehe einsatzverwaltung-taxonomies.php).

Der interessante Part ist die Ausgabe. Derzeit wird hierfür die Methode [wp_dropdown_categories()](https://developer.wordpress.org/reference/functions/wp_dropdown_categories/) verwendet.
https://github.com/abrain/einsatzverwaltung/blob/7b1df93227bbd5df51bec14345d2a6eb1223f918/src/einsatzverwaltung-frontend.php#L86-L102

Deren Verhalten (zumindest das verwendete) müsste nachgebaut werden plus eben die neue Logik für die veralteten Einsatzarten.

**Comment by heikobornholdt** [comment]
Ich habe mich informiert/umgeschaut:
- Die Methode `wp_dropdown_categories()` verwendet intern die Methode `get_terms()`. Letztere Methode bietet durch Actions/Filters (z.B. `get_terms_orderby`) ein paar Einstiegspunkte für unseren Bedarf.
- Das Plugin [Category Order and Taxonomy Terms Order](https://de.wordpress.org/plugins/taxonomy-terms-order/) ermöglicht die beliebige Sortierung von Taxonomien. Dabei wird das bestehende Attribut `term_order` für die Sortierung verwendet. Durch oben genannten Filter wird dafür gesorgt, dass überall die Taxonomien in der gewünschten Reihenfolge dargestellt.

Was hältst du davon, wenn wir das bestehende Attribut `term_order` verwenden? Die GUI für die Verwaltung der Einsatzarten müsste um entsprechende Eingabefelder erweitert werden. Die Sortierung der Einsatzarten sollte zuerst nach dem Attribut `term_order` und dann nach dem Attribut `name` erfolgen.

Folgender Snippet ermöglicht dies:
`````php
add_filter('get_terms_orderby', function($orderby, $args) {
	if ($args['taxonomy'] == array('einsatzart')) {
		return 't.term_order,t.name';
	}
}, 1, 2);
`````

Da standardmäßig das Attribut `term_order` immer den Wert 0 hat, würde sich an dem bisherigen Verhalten der Sortierung nichts ändern. Erst wenn der Anwender aktiv einen Wert für die Reihenfolge angibt, wirkt sich dies auf die Sortierung aus.

Dieser Ansatz erscheint mir mächtiger als das einfaches boolsches Attribut, da man so dem Anwender die volle Kontrolle über die Sortierung gibt.

Bei meinem persönlichen Use-Case würde ich dann den archivierten Einsatzarten einen hohen Wert geben und schon würden diese ans Ende der Liste wandern und so beim Erstellen neuer Einsätze nicht mehr stören.

Was hältst du davon?
