### ISSUE TITLE
Alarmzeit wird bei Facebook falsch angezeigt.

### ISSUE THREAD

**Issue by jhbriese** [abrain/einsatzverwaltung#141]
Verlinkt man auf Facebook einen Einsatzbericht wird als Alarmzeit die Zeit angegeben, zu der der Bericht veröffentlicht wurde.
https://www.facebook.com/ffhelmste/
https://www.feuerwehr-helmste.de/einsatzbericht/verkehrsunfall-in-fredenbeck/
In der Metabeschreibung steht es richtig, keine Ahnung wo Facebook das hernimmt. ¯\_(ツ)_/¯

**Comment by jhbriese** [comment]
Es liegt wohl irgendwie an der zu schnellen Veröffentlichung. Bei uns wurde bisher automatisch und **direkt** bei FB veröffentlicht. In dem Moment, in dem sich FB die Meta Info holt, scheint bei Alarmzeit noch die Beitragszeit stehen. Setzt man bei FB den cache zurück und veröffentlicht erneut läuft es.

**Comment by abrain** [comment]
Richtig, das liegt daran, dass der Beitrag erst einmal so gespeichert wird wie er im Editor zu sehen ist. Direkt im Anschluss werden die Metadaten angelegt, wobei auch das Veröffentlichungsdatum überschrieben wird. Zu diesem Zeitpunkt wurde der Beitrag aber schon an Facebook weitergereicht.

Der einfachste Workaround ist momentan, den Einsatzbericht zeitversetzt bei Facebook zu veröffentlichen. Ein paar Sekunden sollten da schon genügen.

Was die dauerhafte Lösung des Problems angeht, wäre es eine Idee, das Datum schon früher zu setzen bzw. zu überschreiben. Das bringt jedoch wieder andere Probleme mit sich, außerdem löst es nur das Problem mit dem Datum. Es kann genauso passieren, dass die Vorschau auf Facebook keinerlei Fahrzeuge oder sonstige Daten, die von den Metadaten abhängen, anzeigt.

Die beste Lösung wäre in meinen Augen, den Veröffentlichungsstatus so lange auf "Entwurf" zu halten, bis die Metadaten und das korrekte Datum gesetzt sind. Wenn erst dann auf "Veröffentlicht" gesetzt wird, ist der Einsatzbericht nur mit korrekten Daten öffentlich zu sehen und kann bei Facebook nicht falsch angezeigt werden.

**Comment by x2on** [comment]
Das gleiche Problem entsteht wenn man E-Mail Benachrichtigungen verwendet. Dort steht dann bei der Alarmzeit das Veröffentlichungsdatum anstelle der Alarmzeit.

**Comment by abrain** [comment]
@x2on Über welches Plugin werden die Benachrichtungen verschickt?
@jhbriese Mit welchem Plugin macht ihr das Sharing auf Facebook?

**Comment by x2on** [comment]
@abrain https://de.wordpress.org/plugins/bnfw/

**Comment by abrain** [comment]
@x2on Mit welchem Shortcode wird die Benachrichtung generiert? Mit `[post_date]` tritt dieses Problem bei mir nicht auf, auch nicht mit älteren Versionen des Plugins.
