### ISSUE TITLE
Shortcode für Gesamtanzahl der Einsätze im Jahr

### ISSUE THREAD

**Issue by x2on** [abrain/einsatzverwaltung#144]
Einen Shortcode für die Gesamtanzahl der Einsätze im aktuellen Jahr wäre gut. Dann könnte man dies auf der Startseite in ein Widget einbinden.

**Comment by abrain** [comment]
Danke für den Vorschlag. Das müsste eigentlich mit #121 abzubilden sein, oder?

**Comment by x2on** [comment]
Ja wäre auch eine Möglichkeit. 
Das Feature hier habe ich gerade rudimentär umgesetzt, schaue das ich die nächsten Tage einen PR dafür mache.

**Comment by abrain** [comment]
Duplicate of #121
