### ISSUE TITLE
Wochentag bei Alarmierungsdatum in Einsatzbericht

### ISSUE THREAD

**Issue by FiremanLZ4** [abrain/einsatzverwaltung#145]
Ist es möglich in den Einsatzberichten vor das Datum den Wochentag (Mo.-So.) anzeigen zu lassen.
(Weiter so, super Plugin)

**Comment by abrain** [comment]
Die Datums- und Uhrzeitangaben werden gemäß den Einstellungen, die für die ganze WordPress-Instanz gelten, formatiert (Einstellungen > Allgemein). Du kannst dort mit dem angepassten Format den Wochentag dazunehmen.

Es gibt eine Ausnahme: In der Einsatzliste wird das fest eingestellte Format `d.m.Y H:i` verwendet.

(Danke)
