### ISSUE TITLE
CSV Import Alarmzeit

### ISSUE THREAD

**Issue by x2on** [abrain/einsatzverwaltung#146]
Ich versuche gerade über CSV einen Import zu machen, bekomme aber immer folgende Fehlermeldung:

> Die Alarmzeit '16.12.2017 16:45' konnte mit dem angegebenen Format d.m.Y H:i nicht eingelesen werden

Im CSV steht folgende hab ich folgendes drin: `'16.12.2017 16:45'`
Übersehe ich irgendwas? Das ist doch im Format `d.m.Y H:i`, oder?

**Comment by x2on** [comment]
Fehler gefunden, ich hatte in der CSV Datei das Datum in einfachen Anführungszeichen. Wenn man diese entfernt funktioniert es.

**Comment by abrain** [comment]
Danke für die Rückmeldung, werde das bei den Hinweisen zum Dateiaufbau aufnehmen.
