### ISSUE TITLE
Nach CSV-Import werden alle Einsätze auf der Startseite angezeigt

### ISSUE THREAD

**Issue by x2on** [abrain/einsatzverwaltung#147]
Nach dem Import von Einstätzen über CSV und automatischem Veröffentlichen werden diese auch auf der Blog Startseite angezeigt, obwohl hier nur wichtige Einstätze erscheinen sollten.
Nach dem Öffnen eines importierten Einsatzberichtes und erneutem Abspeichern ohne Änderung verschwindet dieser von der Startseite.

**Comment by abrain** [comment]
Danke! Habe das Problem gefunden, wird behoben.
