### ISSUE TITLE
Fahrzeuge im Adminbereich nach eigener Reihenfolge sortieren

### ISSUE THREAD

**Issue by heikobornholdt** [abrain/einsatzverwaltung#149]
Moin,

man kann bei Fahrzeugen ja einen Wert bei "Reihenfolge" angeben.

Kann es sein, dass dieser Wert nicht bei der Sortierung der Fahrzeuge im Adminbereich bei der Auflistung aller Fahrzeuge bzw. beim Erstellen eines Einsatzberichtes berücksichtigt wird?

**Comment by abrain** [comment]
> Kann es sein, dass dieser Wert nicht bei der Sortierung der Fahrzeuge im Adminbereich bei der Auflistung aller Fahrzeuge bzw. beim Erstellen eines Einsatzberichtes berücksichtigt wird?

Das ist richtig, dieser Wert wird aktuell nur bei der Ausgabe in einem Einsatzbericht oder der Einsatzliste beachtet.

**Comment by heikobornholdt** [comment]
Ist das so gewollt?

Ich würde es begrüßen, wenn die Fahrzeuge beim Erstellen eines Einsatzberichtes entsprechend sortiert werden.

**Comment by abrain** [comment]
Das spielt auch irgendwie mit #131 zusammen. Also wenn da schon mal Hand angelegt wird, bietet sich das ja zusammen an.
