### ISSUE TITLE
"besonderer Einsatz" ohne Funktion

### ISSUE THREAD

**Issue by ffkahl** [abrain/einsatzverwaltung#150]
Guten Abend,

bei uns geht die Funktion "besonderer Einsatz" nicht. 
WP4.9.2 mit Plugin 1.3.3.
Beide Hacken bei Einsatzberichte als Beitrag gesetzt. Es werden aber alle Beiträge auf der Startseite angezeigt.
Im Backend werden die "besonderen Einsätze" korrekt mit Stern markiert dargestellt...

Gibt es ähnliche Erkenntnisse oder Workarounds?

thx!
ffk

**Comment by abrain** [comment]
Hallo,
das Problem ist mir so noch nicht bekannt und bei mir lokal konnte ich das nicht nachvollziehen. Welches Theme wird denn verwendet?

**Comment by ffkahl** [comment]
Arclite.
Andere Plugins, die auf Kategorien wirken ebenfalls deaktiviert, ohne
Änderung, bes Einsatz wirkt nicht...

Am 20.01.2018 18:41 schrieb "Andreas Brain" <notifications@github.com>:

**Comment by ffkahl** [comment]
Kann ich irgendwo eine Art Debug einschalten oder etwas testen um dem Problem auf die Schliche zu kommen?

**Comment by ffkahl** [comment]
Zwischenzeitlich habe ich auch testweise auf des Standardtheme 2017 gewechselt. Leider auch ohne Änderung...alle Einsätze sind sichtbar.

**Comment by abrain** [comment]
Wurden die Einsatzberichte importiert? Verschwindet ein Einsatzbericht von der Startseite, wenn er explizit nochmal ohne den Haken bei "besonderer Einsatz" abgespeichert wird?

**Comment by ffkahl** [comment]
Ja, Einsatzberichte wurden aus wp-einsatz übernommen.
Ja, wird der Bericht nochmal ohne "bes Einsatz" gespeichert, verschwindet er von der Startseite.

**Comment by abrain** [comment]
Ok, dann liegt das an #147. Ist zwar bereits behoben, käme aber erst mit Version 1.4.0 raus. Dann schaue ich, dass ich für diese Fehlerbehebung einen kleinen Patch rausgebe, mit dem auch die falsch importierten repariert werden.

**Comment by abrain** [comment]
Tut mir leid, dass es so lange gedauert hat, der Patch ist jetzt draußen.
