### ISSUE TITLE
Beitragsbild auf 100% Breite

### ISSUE THREAD

**Issue by MichelKlomp** [abrain/einsatzverwaltung#151]
Guten Tag,
Ist es möglich, dass sie das Plugin insofern umbauen, dass sich das Beitragsbild automatisch an die Breite des Conatiners in dem es sich befindet anpasst.
Mfg,
Michel

**Comment by abrain** [comment]
Hallo,
leider nein, da die Ausgabe des Beitragsbilds vom Theme veranlasst wird. Ist das Beitragsbild bei den normalen Beiträgen bereits auf 100 % Breite und nur bei den Einsatzberichten nicht?

**Comment by MichelKlomp** [comment]
Ja genau das ist das Problem.
Eingesetztes Theme ist "[The7](https://themeforest.net/item/the7-responsive-multipurpose-wordpress-theme/5556590)".

[Hier ein Beispiel (rechts normaler Beitrag, links ein Einsatzbericht)](https://puu.sh/zdP7d/36aeacefc8.png)

**Comment by abrain** [comment]
In der Regel kommt dieses Phänomen daher, dass das Theme CSS-Klassen definiert, die nur für normale Beiträge funktionieren, aber nicht für zusätzliche Beitragstypen, wie es die Einsatzberichte sind.

Ein normaler Beitrag könnte von folgendem HTML-Tag umschlossen sein:

```html
<article id="post-5126" class="post-5126 post type-post status-publish format-standard has-post-thumbnail hentry category-einkategorie tag-einschlagwort">
```

Entscheidend hier ist die CSS-Klasse post bzw. type-post. Zum Vergleich der gleiche HTML-Tag eines Einstazberichts:

```html
<article id="post-5139" class="post-5139 einsatz type-einsatz status-publish hentry einsatzart-thl-1">
```

Hier gibt es nun nicht mehr die Klassen `post` und `type-post`, sondern `einsatz` und `type-einsatz`. Die Lösung besteht nun darin, die CSS-Stile, die für die normalen Beiträge gelten, auch für die Einsatzberichte gelten zu lassen. Heißt also, die entsprechenden Stile für `post` bzw. `type-post` kopieren und auf `einsatz` bzw. `type-einsatz` umschreiben.

Sofern du nicht schon ein [Child-Theme](https://developer.wordpress.org/themes/advanced-topics/child-themes/) für andere Anpassungen hast, würde ich empfehlen, die Funktion "Zusätzliches CSS" im Customizer zu benutzen.

**Comment by MichelKlomp** [comment]
Super hat geklappt. Vielen Dank für die schnelle Hilfe.
