### ISSUE TITLE
Export/Import der daten

### ISSUE THREAD

**Issue by ole1210** [abrain/einsatzverwaltung#153]
Vielen Dank für das echt hilfreiche Plugin.

Ich betreue ehrenamtlich die Webseite unserer freiwilligen Feuerwehr, wo das Plugin seit geraumer Zeit zum Einsatz kommt. Es läuft einwandfrei.

Nun soll eine Ortsgruppe ebenfalls die gleichen Einsatzberichte veröffentlichen. Welche Möglichkeiten eines automatischen ex- und importes gibt es?

Viele Grüße

**Comment by abrain** [comment]
Ein Export in den Formaten CSV und JSON ist gerade in Arbeit (#132), ein CSV-Import existiert bereits. Mit dem in WordPress eingebauten Export und Import wird meines Wissens nach nicht alles erfasst.

Oder geht es hierbei dann um einen fortlaufenden und automatisierten Abgleich von zwei getrennten WordPress-Installationen?

**Comment by ole1210** [comment]
Hallo Andreas,

eigentlich geht es im einen permanenten Abgleich. Ein manueller Import ist jedoch erstmal besser als nichts. :) Dein Link sagt mir nicht viel, ich habe null Ahnung von github. Was denkst du, wie lange die Entwicklung der Exportfunktion noch dauert?

Denkst du, daraus lässt sich bsp wer Cronjob was permanentes basteln?

Schönen Gruß

Ole

**Comment by ole1210** [comment]
Hallo?

**Comment by abrain** [comment]
Die Entwicklung des Exports ist jetzt fertig und kommt dann mit dem nächsten Update.

Wenn du das automatisieren möchtest, ist es vermutlich einfacher, auf den WordPress-eigenen Export zurückzugreifen. (Ich habe mich nochmal vergewissert, dass in diesem Export alle wichtigen Informationen enthalten sind.) Dieser kann mit [wp-cli](https://make.wordpress.org/cli/handbook/) gesteuert werden (siehe [wp export](https://developer.wordpress.org/cli/commands/export/) und [wp import](https://developer.wordpress.org/cli/commands/import/)).
