### ISSUE TITLE
Nach Schlagworten/Abteilungen sortieren/suchen

### ISSUE THREAD

**Issue by CheapRob** [abrain/einsatzverwaltung#157]
Hallo Team,

es wäre sehr hilfreich, wenn man seine gesamte Einsatzliste irgendwie filtern könnte, sodass man zum Beispiel auf der Seite einfach per Dropdown nach Einsatzstichwort sortieren kann und sich dann die Einsatzliste auf der Seite für den Nutzer aktualisiert, dass er nur die Einsätze nach Filter sieht.

Am aller besten wäre es natürlich, dass man nach Abteilung sortieren kann. Wir haben drei Abteilungen unsere Wehr, und momentan ist es meines Wissens nach noch nicht möglich, eine Einsatzliste entweder nur für eine Abteilung zu erstellen, bzw einfach seine gesamte Einsatzliste nach Abteilung zu sortieren.

Damit würde man auch großen Hauptfeuerwachen mit teilweise fünf oder sechs Abteilungen viel erleichtern.

Ist sowas umsetzbar für Euch oder gibt es hier schon eine Lösung? :)

**Comment by CheapRob** [comment]
Hallo Abrain,

ist dies möglich Einsätze nach Abteilung zuzuteilen?

**Comment by abrain** [comment]
Hallo, das ist derzeit leider nicht möglich. Weder die Zuteilung von Einätzen zu Abteilungen, noch die Filterung der Einsatzliste. Ist aber in Zukunft durchaus denkbar.
