### ISSUE TITLE
Nur einen bestimmten Einsatz in der Liste anzeigen

### ISSUE THREAD

**Issue by CheapRob** [abrain/einsatzverwaltung#158]
Hallo Team,

ist es momentan möglich irgendwie zum Beispiel per ID eines Einsatzes, nur diesen in der Einsatzliste anzeigen zu lassen?

**Comment by abrain** [comment]
Hi,
nein, nach der ID eines Einsatzes kann nicht gefiltert werden. Darf ich fragen, was der Anwendungsfall dafür wäre?

**Comment by abrain** [comment]
Da geht es aber nur darum, einen einzelnen Einsatz im Text zu verlinken, richtig? Seit WordPress 4.4 können Beiträge in andere Beiträge eingebunden werden. Dazu einfach die URL des Beitrags (oder Einsatzberichts) in eine eigene Zeile einfügen. Sieht dann z.B. so aus:

<img width="697" alt="oembeds" src="https://user-images.githubusercontent.com/1263052/42135227-289fb1ea-7d48-11e8-8504-c2c73a049ca8.png">

**Comment by abrain** [comment]
@CheapRob @Henrikkkkkk Ist der Vorschlag im [Kommentar oberhalb](https://github.com/abrain/einsatzverwaltung/issues/158#issuecomment-401609008) für eure Zwecke ebenso ausreichend?

**Comment by Henrikkkkkk** [comment]
Ja das ist so okay

Outlook for Android<https://aka.ms/ghei36> herunterladen

________________________________
