### ISSUE TITLE
Alarmzeit optional

### ISSUE THREAD

**Issue by SchaberMedien** [abrain/einsatzverwaltung#159]
Guten Abend!

Wäre es möglich die Alarmzeit optional zu gestalten? Wenn man keine angibt wird diese als 00:00 übernommen und auch in den Details aufgeführt.

Vielen Dank und beste Grüße!

**Comment by abrain** [comment]
Zum Speichern der Berichte ist eine Uhrzeit auf jeden Fall erforderlich, es wäre aber möglich, die Uhrzeit bei der Anzeige optional zu berücksichtigen.

**Comment by SchaberMedien** [comment]
Das wäre super! Eine Checkbox in den Einstellungen würde da ja schon genügen. Danke

**Comment by abrain** [comment]
Im Widget „Letzte Einsätze (eigenes Format)“ kann die Uhrzeit einfach weggelassen werden, indem der entsprechende Platzhalter `%time%` nicht verwendet wird. Mit Version 1.4.0 (die mit etwas Glück noch dieses Wochenende erscheint) wird es möglich, die Einsatzberichte ebenso durch Templates zu gestalten.

**Comment by abrain** [comment]
Ist die Anfrage noch aktuell oder konnte das mit Hilfe der Templates gelöst werden?
