### ISSUE TITLE
Einsatz ohne Text zeigt in Detailansicht nichts an

### ISSUE THREAD

**Issue by SchaberMedien** [abrain/einsatzverwaltung#160]
Hallo,

beim Anlegen eines Einsatzes ohne Text werden keine Details angezeigt. Auch wenn ein Bild vorhanden ist, wird lediglich das Bild angezeigt, nicht aber Einsatzart, -ort, etc.

**Comment by abrain** [comment]
Wenn der Berichtstext leer gelassen wird, werden eigentlich die Zusatzinformationen wie Art, Ort und Zeit trotzdem angezeigt, und darunter erscheint der Text "Kein Einsatzbericht vorhanden". Wenn überhaupt nichts erscheint, könnte das am Theme liegen. Welches kommt denn zum Einsatz?

**Comment by SchaberMedien** [comment]
Ah okay, das kann natürlich sein. Ich verwende FireDepartment von Ancorathemes http://firedepartment.ancorathemes.com/

**Comment by abrain** [comment]
Bei kommerziellen Themes kann ich leider nicht helfen. Bitte dort mal im Support anfragen, was der Grund sein könnte und ob es umgangen werden kann.
