### ISSUE TITLE
Karte einfügen

### ISSUE THREAD

**Issue by Henrikkkkkk** [abrain/einsatzverwaltung#161]
Hey,
Ich fände es schön, wenn man beispielsweise eine Openstreetmap einfügen könnte, wo der Einsatzort auf einer Karte angezeigt wird. Vielleicht ja auch, wenn es weitergehen soll, eine Übersichtskarte mit allen Einsätzen.

**Comment by VPatrick** [comment]
Siehe Issue #98. Dort gibt es schon eine ähnliche Anforderung. Wie sieht es hier mit der Umsetzung aus?

**Comment by abrain** [comment]
Hierzu habe ich gerade in #98 kommentiert, diesen Issue schließe ich als Duplikat
