### ISSUE TITLE
Probleme mit Site Origin Page Builder

### ISSUE THREAD

**Issue by deeKay93** [abrain/einsatzverwaltung#165]
Hallo,

erstmal ein großer Lob.
Das Plugin hat mir extrem geholfen beim Aufbau von einer Wordpress Seite für meine Feuerwehr.

Leider bin ich aber auf einen Fehler gestoßen:

Durch den Commit 15f88b1c1bcb11ba10dbddb833145892d57d9fec lassen sich die Widgets nicht mehr im Page Builder benutzen. ("Das Widget 000000007fe3bd83000000003bf72d24 ist nicht verfügbar")
Ich habe das Problem gelöst indem ich den Commit reverted habe.

Eine andere Lösung könnte das hier sein: https://stackoverflow.com/questions/39586672/pass-arguments-to-wp-widget-construct-via-register-widget-action-hook

Leider kenne ich mich mit php/Wordpress nicht gut genug aus, um zu wissen, welches die bessere Lösung wäre.

**Comment by abrain** [comment]
Hi,

vielen Dank! Das Problem kann ich in meiner lokalen Installation nachstellen.

Auf der Suche nach den Ursachen bin ich dann auf https://github.com/siteorigin/siteorigin-panels/issues/509 gestoßen, es ist also ein Bug im Page Builder selbst. Ich werde dort nachhaken, dass das gelöst wird.

**Comment by deeKay93** [comment]
Hi,
vielen Dank für die Antwort und dafür, dass du auch in dem anderen Plugin nachgehakt hast.
