### ISSUE TITLE
Gutenberg Unterstützung

### ISSUE THREAD

**Issue by silas229** [abrain/einsatzverwaltung#170]
Wird Einsatzverwaltung den neuen Gutenberg Editor, der bereits am 27. Nov. mit WordPress 5.0 erscheint, unterstützen?

**Comment by abrain** [comment]
Der Gutenberg-Editor wird leider nicht ab Tag 1 unterstützt. Bisher hatte ich noch nicht die Zeit, das ausreichend zu testen. Speziell die Metabox unter dem Editor wird sich vermutlich verändern müssen.

Bei einem Upgrade auf WordPress 5.0 bleibt jedoch der klassische Editor erhalten und die Einsatzberichte können weiterhin editiert werden.

**Comment by abrain** [comment]
Basis-Support für den neuen Editor ist eingebaut

**Comment by silas229** [comment]
Wann wird diese Version etwa erscheinen?

**Comment by abrain** [comment]
Sie soll spätestens mit WordPress 5.1 (21. Februar 2019) erscheinen.

**Comment by Frankiii1984** [comment]
Hi,

beim wechsel auf ein neues Theme mit Gutenberg, wird mir bei der Anzeige der Einsatzberichte im Detail, wird der Bereich "Weitere Kräfte" ganz Links am Bildschirmrand angezeigt. Kann man das selbständig ändern?

![image](https://github.com/abrain/einsatzverwaltung/assets/141424814/8e769ed0-60ae-4ae9-b43c-26048a393034)

**Comment by silas229** [comment]
@Frankiii1984 Benutzt das Theme schon Full-Site-Editing? Oder ist es das ganz normale Template, das in den [Einstellungen](https://einsatzverwaltung.org/dokumentation/templates/) konfiguriert werden kann?

**Comment by Frankiii1984** [comment]
@silas229 ich gehe davon aus, dass es schon Full-Site-Editing nutzt, da ich im z. B. im Berichtseditor und auch bei den Einsatzberichten alles auf volle Seitenbreite einstellen kann.

**Comment by silas229** [comment]
@Frankiii1984 Gibt es im Backend unter Design den Menüpunkt Editor?
