### ISSUE TITLE
Hierarchie der Einsatzart wird bei Template nicht angezeigt

### ISSUE THREAD

**Issue by silas229** [abrain/einsatzverwaltung#171]
Wenn ich in den Einstellungen unter Einsatzliste, die Hierarchie der Einsatzart aktiviere, wird das nur übernommen wenn ich kein Template für die Einsatzberichte verwende.

**Comment by silas229** [comment]
Der Fehler ist, denke ich, hier:
https://github.com/abrain/einsatzverwaltung/blob/6f7d33de296b834a0dbf2ff820e033114c2fec9b/src/Util/Formatter.php#L124-L126

**Comment by abrain** [comment]
Die Einstellung ist eigentlich nur für die Einsatzliste gedacht und sollte sich nicht auf die Einzelansicht der Einsatzberichte auswirken. Allerdings ist das tatsächlich eine Inkonsistenz, denn in der klassischen Ansicht ohne Template wird die Hierarchie immer angezeigt:
https://github.com/abrain/einsatzverwaltung/blob/6f7d33de296b834a0dbf2ff820e033114c2fec9b/src/Frontend.php#L94
(Durch Weglassen des vierten Parameters wird der Standardwert `true` angewendet)
