### ISSUE TITLE
CSV importieren funktioniert nicht

### ISSUE THREAD

**Issue by Mululu** [abrain/einsatzverwaltung#175]
Hallo,

Ich kann die erstellte .CSV Datei vom Einsatzverwaltungsplugin nicht wieder importieren. 

Ich lade die .CSV Datei wie angegeben hoch aber nirgends gibt es eine Auswahlmöglichkeit der Datei.

![unbenannt](https://user-images.githubusercontent.com/5918495/50600493-8aab6780-0eb1-11e9-9c1e-0ec1f7eae5d7.JPG)

**Comment by abrain** [comment]
Wird die Datei erfolgreich hochgeladen und taucht dann in der Medienübersicht auf?

Mit WordPress 5.0.1 wurde die [Prüfung der hochgeladenen Dateien verschärft](https://make.wordpress.org/core/2018/12/13/backwards-compatibility-breaks-in-5-0-1/), wodurch bestimmte Dateitypen (unter anderem CSV) abgelehnt werden (WordPress bug [45615](https://core.trac.wordpress.org/ticket/45615)).

**Comment by Mululu** [comment]
Anfangs konnte die .csv nicht hochgeladen werden. habe dann folgende Zeile der wp_config hinzugefügt.

define( 'ALLOW_UNFILTERED_UPLOADS', true );

danach funktionierte der Upload problemlos und die .csv wird auch in der Medienübersicht angezeigt aber nicht beim importieren oder sonst irgendwo

**Comment by abrain** [comment]
Welcher Dateityp wird in den Anhang-Details für diese Datei angezeigt (vgl. Screenshot `text/csv`)?
![csv_filetype](https://user-images.githubusercontent.com/1263052/50612995-5bf6b680-0edc-11e9-83c8-d050fc3cfe2a.png)

**Comment by abrain** [comment]
Mit dem Update auf WordPress 5.0.3 wurde die Upload-Funktion repariert, nun können auch CSV-Dateien wieder hochgeladen werden. `ALLOW_UNFILTERED_UPLOADS` sollte daher nicht mehr nötig sein.

Besteht das Problem beim Import weiter? (Auch mit neu hochgeladenen Dateien?)

**Comment by danielmg112** [comment]
Hi, 
wir haben das selbe oder ein Ähnliches Problem, hochladen der csv kein Problem aber der Importer findet die csv Datei in der Mediathek nicht.

Plugin: 1.7.0, WordPress: 5.5.1, PHP: 7.3.10

csv liegt unter [...]uploads/2020/09/___einsatzberichte.csv

Displaytext im Importer:
[...]
In der Mediathek gefundene CSV-Dateien
Bevor eine Datei für den Import verwendet werden kann, muss sie in die Mediathek hochgeladen worden sein. Nach erfolgreichem Import kann die Datei gelöscht werden.
Der Inhalt der Mediathek ist öffentlich abrufbar. Achte darauf, dass die Importdatei keine sensiblen Daten enthält.

Keine CSV-Dateien gefunden.
[...]
Danke im Vorraus.
