### ISSUE TITLE
Editor integrieren

### ISSUE THREAD

**Issue by Mululu** [abrain/einsatzverwaltung#178]
Hallo,

mir ist jetzt bei vielen Themes bereits aufgefallen das im Einsatzeditor viele Funktionen des jeweiligen Themes fehlen. z.b.: Slider im Header einbinden mit overlapping Funktion oder Designeinstellungen, Änderungen von CCS Styles werden nicht bei Einsatzberichten übernommen etc.

Ist es nicht möglich/sinnvoll immer die Editorbasis von jeweiligem Theme zu nehmen und bloß den Einsatzeditor zu integrieren? Es wird ja dafür bestimmt irgendwelche Funktionen, Variablen, Parameter oder wie man das nennt geben und das zu ermöglichen.

**Comment by abrain** [comment]
Ein Editor, den das Theme bereitstellt, ist mir so noch nicht untergekommen. Der Editor wird vom WordPress Core gestellt und Plugins und Themes können ihn anreichern. Entsprechend liegt auch die Entscheidung, für welche Beitragstypen der Editor erweitert wird, bei den jeweiligen Themes und Plugins.

Wenn ein Theme nur die eingebauten Beitragstypen (Beitrag, Seite, Anhang, ...) beachtet, nicht aber durch Plugins hinzugefügte (wie die Einsatzberichte), habe ich darauf in der Regel keinen Einfluss. Das ist auch der Hintergrund, warum es sein kann, dass Einsatzberichte nicht wie die Beiträge aussehen. Zur Lösung des Designproblems gibt es einen [Blogpost](https://einsatzverwaltung.abrain.de/2018/12/wenn-sich-einsatzberichte-nicht-dem-design-der-seite-anpassen/).

Kannst du mir ein Theme aus dem [Theme Directory](https://wordpress.org/themes/) nennen, bei dem ich mir diese zusätzlichen Editorfunktionen ansehen kann?

**Comment by Mululu** [comment]
Das dass an den Themes liegt wusste ich nicht. Ich habe jetzt vom Theme Support eine Code bekommen.

`add_filter('avf_builder_boxes', 'add_builder_to_posttype');

function add_builder_to_posttype($metabox)
{
  foreach($metabox as &$meta)
  {
    if($meta['id'] == 'avia_builder' || $meta['id'] == 'layout')
    {
      $meta['page'][] = 'post'; /*instead add the name of the custom post type here*/
    }
  }
  

  return $metabox;
}`

das "post" habe ich durch "einsatz" ersetzt. Leider funktioniert das nicht.

**Comment by Mululu** [comment]
Kommando zurück. Funktioniert nach einen Webserver Neustart.

**Comment by abrain** [comment]
Super, dann hat sich das ja geklärt :)
