### ISSUE TITLE
Beiträge erscheinen trotz deaktivierter Einstellung im Beitragsarchiv

### ISSUE THREAD

**Issue by babsitz** [abrain/einsatzverwaltung#179]
Hallo, 

ich habe in den Einstellungen die Option, dass die Einsatzberichte im Archiv angezeigt werden deaktiviert, aber trotzdem erscheinen die Einsätze im Beitragsarchiv.

Grüße
Jörg

**Comment by abrain** [comment]
Hallo,
um den Fehlerbericht besser nachvollziehen zu können, bräuchte ich bitte noch folgende Angaben:
- In welcher Version wird das Plugin eingesetzt? 
- Welches Theme kommt zum Einsatz?
- Passiert das nur im Beitragsarchiv oder auch z.B. im RSS-Feed oder sofern vorhanden im Widget "Neueste Beiträge"?
- Was ist bei den beiden verwandten Einstellungen (Kategorie für Einsatzberichte, nur besondere Einsätze im Archiv) gesetzt?

**Comment by babsitz** [comment]
Sorry, habe den Fehler gefunden. Der Part „Davon unabhängig“ ist mir entgangen. Tut mir echt leid.

**Comment by abrain** [comment]
Kein Problem :)
