### ISSUE TITLE
"Memory Size Error" auf der Fahrzeuge-Seite

### ISSUE THREAD

**Issue by Markkuuss** [abrain/einsatzverwaltung#183]
Ich habe eben meine Plugins aktualisiert und Wordpress auf 5.2.2 geupdatet. Nun wird plötzlich auf der Fahrzeug-Seite so viel Speicher allokiert:

![image](https://user-images.githubusercontent.com/10926460/60032259-7b5de780-96a6-11e9-8bc8-444d42c3f20f.png)

Mein WP_MEMORY_LIMIT steht aktuell auf 128M, mehr geht leider nicht. Ist das vielleicht ein Fehler im Plugin oder an was könnte es sonst liegen?

**Comment by Markkuuss** [comment]
Ich könnte das Problem mittlerweile weiter eingrenzen. Das Problem ist, dass für die Fahrzeugseiten sämtlich Blogbeiträge und Seiten im Dropdown aufgelistet werden. Ich habe ein Kalender Plugin, das für jeden Termin ein Post erstellt. Diese werden natürlich auch alle aufgelistet. Nachdem es sehr viele Termine sind, kommt es hier zu dem Speicher Fehler. Wäre es nicht möglich, dass man hier nur Seiten und Portfolio Einträge anzeigt oder es irgendwie anders eingrenzt?

**Comment by abrain** [comment]
Danke für den Fehlerbericht und die Suche nach der Ursache. Ursprünglich konnten dort nur Seiten ausgewählt werden, was bei einzelnen Installationen nicht ausreichend war. Entsprechend werden jetzt alle verfügbaren Einträge angezeigt, abzüglich die von Inhaltstypen, die keinen Sinn ergeben (z.B. Einsatzberichte und Anhänge). Auch Kalendereinträge werden schon gefiltert, aber nur die, die mir bekannt waren.

https://github.com/abrain/einsatzverwaltung/blob/e4f2d208053ea357b08f0d23d3972f3b370a4982/src/Types/Vehicle.php#L72

Ein Workaround wäre, in dieses Array den Beitragstyp des verwendeten Kalender-Plugins einzufügen.

Den könnte ich auch in die Liste aufnehmen, damit das anderen Seiten nicht passiert.

Um das Problem in Zukunft ganz zu umgehen, wäre eine zweistufige Auswahl denkbar. Erst nach der Auswahl des Inhaltstyps wird die Liste mit den Einträgen gefüllt und auch nur für diesen Inhaltstyp.

**Comment by Markkuuss** [comment]
> https://github.com/abrain/einsatzverwaltung/blob/e4f2d208053ea357b08f0d23d3972f3b370a4982/src/Types/Vehicle.php#L72
> 
> Ein Workaround wäre, in dieses Array den Beitragstyp des verwendeten Kalender-Plugins einzufügen.
> 
> Den könnte ich auch in die Liste aufnehmen, damit das anderen Seiten nicht passiert.

Perfekt, wie ich sehe, sind auch schon andere Kalender-Beitragstyp ausgenommen worden.
In das Array müsste man noch "pec-events" aufnehmen.

> Um das Problem in Zukunft ganz zu umgehen, wäre eine zweistufige Auswahl denkbar. Erst nach der Auswahl des Inhaltstyps wird die Liste mit den Einträgen gefüllt und auch nur für diesen Inhaltstyp.

Das wäre natürlich noch perfekter. :-) Erstmal sollte es reichen, wenn die Termine ausgenommen sind.

Vielleicht macht es auch Sinn, alle Beitragstypen auszunehmen, die die Bezeichnung "event" beinhalten?

**Comment by abrain** [comment]
Behoben, es können in dem Dropdown nur noch Seiten ausgewählt werden. Mit #109 gibt es jetzt ein zusätzliches Feld für URLs. Dort können entweder URLs zu externen Seiten eingegeben werden oder aber auch Links zu beliebigen Inhalten auf der eigenen Seite.
