### ISSUE TITLE
Einheiten-Fenster im Bearbeiten-Bildschirm der Mehrfachauswahl

### ISSUE THREAD

**Issue by CheapRob** [abrain/einsatzverwaltung#185]
Ist es möglich, die Einheiten-Liste bei der Mehrfachbearbeitung hinzuzufügen?
Da ich jetzt für circa 450 Einsätze nachträglich die Einheiten einpflegen muss, wäre es perfekt, wenn man dies über die Mehrfachauswahl/Bearbeitung abwickeln könnte

**Comment by abrain** [comment]
Zu Beginn war ich mir nicht ganz sicher, ob und wenn ja wie schnell das Feature gebaut werden könnte. Jetzt ist es fertig und kommt mit dem nächsten Update.
