### ISSUE TITLE
Kategorie Anzeigen

### ISSUE THREAD

**Issue by wp-daved** [abrain/einsatzverwaltung#187]
Hallo,
ich bin leider absolut Neu auf dem Gebiet Wordpress.
Ich bin aktuell dabei eine neue Webseite zu bauen und habe mich für das Theme "CoverNews" entschieden. 
Das Plugin ist echt hammer! Allerdings stoße ich nun leider auf ein Problem ..
Beim Anzeigen der Beiträge werden "normale" Beiträge mit der Kategorie angezeigt. Die Einsätze bekommen diesen Banner leider nicht (Sie haben die Kategorie "Einsätze", etc. bekommen). Ist es möglich den Banner auf dem die Kategorie steht  auch für die Einsätze anzeigen zu lassen?
Alternativ würde ich mich auch sehr über Theme Vorschläge freuen für die das Plugin super geeignet ist. 

https://www.bilder-upload.eu/bild-c254de-1565985514.png.html

Ein Bild vom Problem habe ich mal als Link angefügt. Der Beitrag in der Mitte ist ein ganz normaler Beitrag (FEUER TEST). Die beiden anderen links und rechts (FEUER TEST2 u. Feuer Hecke/Busch) sind über die Einsatzverwaltung angelegt.

Freue mich über jeden Tipp oder Hinweis!
Gruß 
Daved

**Comment by abrain** [comment]
Hallo Daved,

ohne die Seite selbst zu sehen, kann ich es nicht mit Sicherheit sagen, aber mein Tipp wäre, dass es sich nur um ein CSS-Problem handelt. Das Problem und die Lösung dazu habe ich im Blog unter dem Titel [Wenn sich Einsatzberichte nicht dem Design der Seite anpassen](https://einsatzverwaltung.abrain.de/2018/12/wenn-sich-einsatzberichte-nicht-dem-design-der-seite-anpassen/) beschrieben. Schau mal, ob dir das weiterhilft.

Empfehlungen für Themes habe ich nicht direkt. Selbst das Theme, das ich bei meiner eigenen Feuerwehr einsetze, würde ich ungern empfehlen, da es schon länger keine Updates mehr bekommen hat. Aber du kannst dich gerne bei den [Referenzen](https://einsatzverwaltung.abrain.de/referenzen/) umsehen, mit welchen Themes das Plugin so verwendet wird. (Manche Themes schreiben ihren Namen in die Fußzeile, manchmal muss man aber auch im HTML-Code nachsehen und nach `/wp-content/themes/` suchen.)

Viele Grüße,
Andreas

**Comment by abrain** [comment]
Hallo @wp-daved , konnstest du das Problem lösen?
