### ISSUE TITLE
Datumformat wird bei CSV Import nicht angenommen

### ISSUE THREAD

**Issue by CheapRob** [abrain/einsatzverwaltung#188]
Ich versuche, Einsätze mit dem CSV-Import zu importieren und habe in der Zelle in Excel für Alarmzeit und Einsatzende das Format "JJJJ-MM-TT hh:mm", allerdings sagt mir dann das Plugin beim Import "Importvorbereitung abgebrochen, Ursache: Die Alarmzeit Alarmzeit konnte mit dem angegebenen Format Y-m-d H:i nicht eingelesen werden"
Gibt es eine Liste, in der steht, wie das Format in Excel aussehen muss, damit das Plugin dies annimmt?

Grüße,
Robin

**Comment by abrain** [comment]
> Die Alarmzeit Alarmzeit konnte mit dem angegebenen Format Y-m-d H:i nicht eingelesen werden

Das Plugin versucht, das Wort "Alarmzeit" mit dem angegebenen Format in ein Datum zu verwandeln, was natürlich fehlschlägt. Hast du den Haken bei _Erste Zeile der Datei enthält Spaltenbeschriftung_ gesetzt? Oder hat die Datei vielleicht die Spaltenbeschriftung zusätlich in einer weiteren Zeile außer der ersten?

**Comment by CheapRob** [comment]
Hallo!
Hab's hinbekommen. Trotz Haken in "Erste Zeile enthält Überschrift" hat er die erste Zeile als Einsatz interpretiert, hab diese jetzt rausgenommen und dann hat's funktioniert.

Was mir aufgefallen ist: Im Einsatzbericht importieren gibt es noch keine Spalte für "Einheiten", ist das nochi n nächsten Update angedacht?

**Comment by abrain** [comment]
> Was mir aufgefallen ist: Im Einsatzbericht importieren gibt es noch keine Spalte für "Einheiten", ist das nochi n nächsten Update angedacht?

Stimmt, ist mir auch die Tage aufgefallen, weil ich das für die Fahrzeuge umbauen muss. Kommt mit dem nächsten Update mit.
