### ISSUE TITLE
Mehrere Einsätze unter einem Eintrag erfassen

### ISSUE THREAD

**Issue by tannenbaum5** [abrain/einsatzverwaltung#192]
Es wäre wünschenswert, wenn es ein Feld "Anzahl" im Einsatzbericht gibt. Klassisches Beispiel sind Unwettereinsätze, bei denen auf eine Alarmierung mehrere Einsätze folgen, die man dann mit einem Bericht abhandeln könnte.

Ich habe das jetzt über ein ACF Feld gelöst und die Funktion updateSequenceNumbers in der Datei Data.php so bearbeitet, dass sie dieses Feld entsprechend nutzt.
Vielleicht nicht die sauberste Lösung aber so sieht das grade aus:

        foreach ($years as $year) {
            $posts = self::getEinsatzberichte($year);

            $expectedNumber = 1;
            foreach ($posts as $post) {
                $actualNumber = get_post_meta($post->ID, 'einsatz_seqNum', true);
                $reportCount = get_post_meta($post->ID, 'einsatz_anzahl', true);

                if ($reportCount > 1)
                {
                    $this->setSequenceNumber($post->ID, ($expectedNumber.' - '.($expectedNumber+$reportCount-1)));
                    $expectedNumber = ($expectedNumber+$reportCount);
                }
                else
                {
                  $this->setSequenceNumber($post->ID, $expectedNumber);
                  $expectedNumber++;
                }
                $actualNumber = 0;
                $reportCount = 0;
            }
        }

Da das aber natürlich bei jedem Update des Plugins wieder futsch ist wäre es toll, wenn diese Option angeboten werden würde.

**Comment by abrain** [comment]
Danke für den Vorschlag und das Codebeispiel. Diese Thematik wird bereits in #116 getrackt.

Duplicate of #116
