### ISSUE TITLE
Einheiten - Link zur Detailseite

### ISSUE THREAD

**Issue by tobiby** [abrain/einsatzverwaltung#196]
Ähnlich wie bei den Fahrzeugen wäre es hilfreich, für jede Einheit einen Link zu einer Seite angeben zu können.
Im Einsatzbericht sollten dann die Einheiten auf die angegebene Seite verlinkt sein.

**Comment by abrain** [comment]
Richtig, das fehlt noch. Danke für den Hinweis.

**Comment by abrain** [comment]
Eingebaut, kommt mit dem nächsten Release
