### ISSUE TITLE
Archivseiten unter den Wordpress-Seiten sichtbar machen

### ISSUE THREAD

**Issue by CheapRob** [abrain/einsatzverwaltung#197]
Gibt es eine Möglichkeit, die Archivseiten (/einsatzberichte/2018, /einsatzberichte/2019, etc...) als eigenständige Seiten in der Seitenliste von WordPress an zu zeigen? 
Momentan liegen die Archivseiten direkt unter der Startseite (Startseite -> 2018), schön wäre es aber, wenn diese unter der Einsatzliste oder direkt in einem Archiv liegen (Startseite -> Einsätze -> Archiv -> 2018), so dass man, wenn man eine Seite zurück geht, nicht direkt auf der Startseite landet, sondern nur eine Ebene weiter oben.
Grüße,
Robin

**Comment by abrain** [comment]
Geht es dabei um die Breadcrumb-Navigation?

**Comment by CheapRob** [comment]
Ja genau

**Comment by abrain** [comment]
Das mit der Breadcrumb-Navigation wurde in #199 behandelt. Beim erneuten Lesen ist mir aufgefallen, dass du von einer "Seitenliste" sprichst. Welche genau meinst du? Hättest du vielleicht einen Screenshot?
