### ISSUE TITLE
Archivseite wird nicht angelegt

### ISSUE THREAD

**Issue by Anderl94** [abrain/einsatzverwaltung#198]
Es werden keine Archivseiten mehr angelegt. Bei den Jahren 2020-2018 funktionierte es wunderbar, jedoch ab 2017 verläuft der link ins leere.
Die Einsätze werden angelegt und sind auch erreichbar.
https://www.ffw-wolframs-eschenbach.de/aktive-wehr/einsaetze/

**Comment by abrain** [comment]
Hallo,
es scheint wieder zu gehen? Lag die Ursache am Plugin oder an etwas anderem?

**Comment by Anderl94** [comment]
Nach umstellen der Wordpress eigenen Permalink-Einstellungen ging es wieder. Warum jedoch nur die Jahre von 2013-2017 im Archiv nicht funktionierten und alle weiteren Jahre schon ist mir nicht klar.

**Comment by abrain** [comment]
> Warum jedoch nur die Jahre von 2013-2017 im Archiv nicht funktionierten und alle weiteren Jahre schon ist mir nicht klar.

Ja, das ist mir auch nicht ganz klar. 🤔
