### ISSUE TITLE
Einsätze unter anderer Seite ordnen

### ISSUE THREAD

**Issue by CheapRob** [abrain/einsatzverwaltung#199]
Hallo,
bei uns ist es momentan so, dass wenn wir in einen Einsatzbericht gehen, steht dieser direkt unter der Startseite (Also Startseite / "Name Einsatzbericht"). Gibt es hier eine Möglichkeit, die Einsätze wo anders unter zu ordnen? Dass man da auf die vorherige Seite kommt? (Also Startseite / Abteilung Soundso / Einsätze / "Name Einsatzbericht")?
Siehe Bild, wie es momentan ist, eventuell für ein Livebeispiel auf unserer Homepage vorbeischauen "feuerwehr-neckarsulm.de", da ist in den Abteilungen ein reiter Einsätze mit der Vorschau von 5 Einsätzen, auf diese Abteilungsseite wollen wir dann zurück bzw wollen wir im Seitenpfad drin haben (siehe Bild unten ganz rechts dieses "Startseite / Einsatz")

![grafik](https://user-images.githubusercontent.com/40196151/75019971-186d5c00-5492-11ea-9c1c-f433d347e84f.png)

**Comment by abrain** [comment]
Die Breadcrumb-Navigation ("Startseite / Rauchentwicklung Wohngebäude") ist kein Feature von WordPress, das wird vom Theme mitgebracht. Ich habe mir gerade mal die kostenlose Variante des Themes angeschaut. Die Funktion `spicepress_breadcrumbs()` kann wohl erweitert bzw. überschrieben werden.

Da es sich um eine Anpassung für eine einzelne Seite bzw. ein bestimmtes Theme handelt, liegt das jenseits von dem was ich mit diesem Plugin leisten kann.
