### ISSUE TITLE
Falsche Einsatzdauer bei Zeitumstellung

### ISSUE THREAD

**Issue by heikobornholdt** [abrain/einsatzverwaltung#200]
Wenn ein Einsatz während einer Zeitumstellung stattfindet, ist die Berechnung der Einsatzdauer falsch.

Alarmzeit: 29.03.2020 01:49 (Winterzeit)
Einsatzende: 29.03.2020 03:15 (Sommerzeit)
Korrekte Dauer: 26m
Berechnete Dauer: 1h 26m

Zeitzone: Europe/Berlin

**Comment by abrain** [comment]
Ist behoben, Update kommt gleich raus
