### ISSUE TITLE
Jahresarchiv bearbeiten

### ISSUE THREAD

**Issue by Venxor** [abrain/einsatzverwaltung#203]
Hallo, 
gibt es die Möglichkeit das Jahresarchiv in folgendem Layout darzustellen?

Nr. 00
Datum: 00.00.0000   Uhrzeit: 00:00   Meldung: Brand 
Einsatzort
Fahrzeuge: ELW, LF, GW-T   mehr...

Wenn ja welche Dateien müssen dafür bearbeitet werden oder welche Einstellung müssen gemacht werden

Mit freundlichen Grüßen 
Oliver

**Comment by abrain** [comment]
Hallo Olvier,

unter Einstellungen > Einsatzverwaltung > Einsatzberichte kannst du bei "Template für Auszug" ein eigenes Aussehen für den Vorschautext (Auszug) festlegen.

Dein Format oben könnte dann so aussehen:

```
Nr. %seqNum%
Datum: %date% Uhrzeit: %time% Meldung: %title%
%location%
Fahrzeuge: %vehicles%
```

Den Haken bei _Template verwenden_ dann nicht vergessen.

[Dokumentation zu Templates und Platzhaltern](https://einsatzverwaltung.abrain.de/dokumentation/templates/)

Klappt das?

Viele Grüße,
Andreas

**Comment by Venxor** [comment]
Hallo Andreas,

ja hat funktioniert!
Vielen Dank für die schnelle Antwort. 

Viele Grüße,
Oliver

**Comment by abrain** [comment]
👍 Gerne
