### ISSUE TITLE
FE2 und WordPress

### ISSUE THREAD

**Issue by djhesepe** [abrain/einsatzverwaltung#205]
Hallo,

Ich hab hier eine Art Anleitung gesehen wie man FE2 in WordPress einbindet. Leider bin ich ein absoluter Laie und bräuchte eure Hilfe wie genau das ganze funktioniert, was ich tun muss damit die Einsätze automatisch auf der Website erscheinen.

Ich hoffe ihr könnt mir helfen.

Gruß

**Comment by freakms** [comment]
Gleiches hier. Ich benötige da auch einmal support.

**Comment by benediktlo** [comment]
Hallo,
ich würde hier auch einmal Hilfe benötigen - würde das ganze gerne auch so einrichten mit FE2 und Wordpress.
Danke!

**Comment by abrain** [comment]
Stand heute (Einsatzverwaltung Version 1.7.2) ist folgendes nötig:
- Ein Benutzer, der Einsatzberichte anlegen und veröffentlichen kann. Aus Sicherheitsgründen bietet es sich an, einen separaten Benutzer anzulegen, der nur die Rechte `edit_einsatzberichte`, `publish_einsatzberichte` und `edit_published_einsatzberichte` hat. Die genannten Rechte können mit einem Plugin wie [User Role Editor](https://de.wordpress.org/plugins/user-role-editor/) vergeben werden.
- Das Plugin [JWT Authentication for WP REST API](https://de.wordpress.org/plugins/jwt-authentication-for-wp-rest-api/), damit FE2 sich anmelden kann.
- In der Datei `wp-content/plugins/einsatzverwaltung/Types/Report.php` in Zeile 212 den Wert für `show_in_rest` von `false` auf `true` setzen.
https://github.com/abrain/einsatzverwaltung/blob/8c24f60c4e451af12cd30aea014639be59717b42/src/Types/Report.php#L206-L213

Die Konfiguration in FE2 ist hier beschrieben: https://alamos-support.atlassian.net/wiki/spaces/documentation/pages/753958913/Einsatzverwaltung

**Disclaimer:** Die oben beschriebene Variante ist eine Übergangslösung und kann sich in Zukunft ändern. Das JWT-Plugin wird nicht mehr aktiv weiterentwickelt und kann Fehler aufweisen.

**Comment by abrain** [comment]
> Jetzt noch eine Frage, wie erreiche ich das der Einsatz nur als Entwurf angelegt wird und nicht sofort veröffentlicht wird?

Dazu müsste FE2 in der Anfrage einen Parameter anders setzen, das wird aber voraussichtlich nicht kurzfristig passieren (siehe https://github.com/abrain/einsatzverwaltung/issues/143#issuecomment-763897797). Wie oben angesprochen, ist die aktuelle Lösung eine Übergangslösung. Mit WordPress 5.6 haben sich nun die Bedingungen für eine ordentliche Lösung ergeben. Als nächstes muss ich nun einen neuen API-Endpunkt in das Plugin einbauen, den FE2 dann nutzen kann. In dem Zuge erübrigen sich die oben angegebenen Schritte komplett.

**Comment by abrain** [comment]
Der neue API-Endpunkt ist in der eben erschienenen [Version 1.10.0](https://einsatzverwaltung.org/2021/11/version-1-10-0/) enthalten. In FE2 soll die Unterstützung dann mit Version 2.24 kommen.
