### ISSUE TITLE
CSV Datei wird nicht in Mediathek erkannt

### ISSUE THREAD

**Issue by Nekarias** [abrain/einsatzverwaltung#206]
Sry für das Duplikat. Das hier gerne schließen und im Originalpost fortführen.
________________
Hi, 
wir haben das selbe oder ein Ähnliches Problem, hochladen der csv kein Problem aber der Importer findet die csv Datei in der Mediathek nicht.

Plugin: 1.7.0, WordPress: 5.5.1, PHP: 7.3.10

csv liegt unter [...]uploads/2020/09/___einsatzberichte.csv

Displaytext im Importer:
[...]
In der Mediathek gefundene CSV-Dateien
Bevor eine Datei für den Import verwendet werden kann, muss sie in die Mediathek hochgeladen worden sein. Nach erfolgreichem Import kann die Datei gelöscht werden.
Der Inhalt der Mediathek ist öffentlich abrufbar. Achte darauf, dass die Importdatei keine sensiblen Daten enthält.

Keine CSV-Dateien gefunden.
[...]
Danke im Vorraus.

_Originally posted by @danielmg112 in https://github.com/abrain/einsatzverwaltung/issues/175#issuecomment-696832899_

**Comment by abrain** [comment]
Hallo,

ich mache trotzdem mal in diesem Issue weiter, da der andere schon länger geschlossen ist. /cc @danielmg112

Wahrscheinlich liegt es daran, dass die Datei in der Mediathek nicht mit dem Dateityp `text/csv` hinterlegt ist. (In der Mediathek auf die Datei klicken, siehe https://github.com/abrain/einsatzverwaltung/issues/175#issuecomment-450988722). Welcher Dateityp wird hier angezeigt?

**Comment by Nekarias** [comment]
![image](https://user-images.githubusercontent.com/7510722/94161971-86459000-fe86-11ea-8521-e929ac70ee85.png)

Dateityp wird nicht als text/csv sondern csv angegeben. Dürfte für den Dateityp aber keinen Unterschied machen?

**Comment by abrain** [comment]
Ah, wieder was gelernt. Hierfür gibt es zwei verschiedene Ansichten und die beiden sind nicht ganz gleich.

Zu der Ansicht, die ich meinte, kommt man, wenn die Mediathek nicht als Liste, sondern als Gitter dargestellt wird.

![Bildschirmfoto 2020-09-24 um 18 04 37](https://user-images.githubusercontent.com/1263052/94170595-8d719b80-fe90-11ea-9c76-d84bbf390ff6.png)

**Comment by Nekarias** [comment]
Ah, Danke!
Wert stand auf application/vnd.ms-excel. Der MIME Type wurde durch Excel in Windows geändert. In der Registry unter "\HKEY_LOCAL_MACHINE\SOFTWARE\Classes\.csv" den Eintrag von "application/vnd.ms-excel" zu "text/csv" ändern hilft.
