### ISSUE TITLE
Import von Einsätzen

### ISSUE THREAD

**Issue by benedikt5201** [abrain/einsatzverwaltung#211]
Hallo,
ich bekomme beim Import immer die Fehlermeldung: Pflichtfeld Alarmzeit wurde nicht zugeordnet
Es ist auch egal was ich mache der Fehler kommt immer. Folgend kurz was ich alles versucht habe:

- Export der Einsätze, damit ich das korrekte Format für den Import habe.
- Export-Liste um neue Einsätze ergänzt
- Versucht Liste zu Importieren mit Spaltenüberschrift, ohne Spaltenüberschrift dann auch mal nur 2-3 Einsätze aber ich bekomme die Liste nicht importiert...

Vielleicht hat ja hier jemand eine Idee was ich falsch machen könnte bzw. wo das Problem liegt...

**Comment by abrain** [comment]
Wenn der Fehler "Pflichtfeld Alarmzeit wurde nicht zugeordnet" kommt, sollte es nicht am Format der Datei liegen. Es ist an sich auch kein festes Format der Import-Datei vorgeschrieben, zumindest was die Spalten und deren Namen angeht. Daher gibt es nach der Auswahl der Datei einen Schritt zur Zuordnung der Spalten zu den Daten in der Einsatzverwaltung.

![Bildschirmfoto 2020-11-22 um 00 13 58](https://user-images.githubusercontent.com/1263052/99889697-f8a0d980-2c57-11eb-9b46-b260017c5740.png)

Dabei muss "Alarmzeit" bei genau einem Feld ausgewählt sein, da ohne die Alarmzeit ein Einsatzbericht nicht importiert werden kann.

**Comment by benedikt5201** [comment]
Danke, der Fehler ist jetzt weg das hat funktioniert - aber jetzt erhalte ich egal was ich mache folgenden Fehler:

"Import abgebrochen, Ursache: Konnte Einsatz nicht importieren: Der Beitrag konnte nicht in die Datenbank eingefügt werden."

Meine Frage, wäre warum kann er es nicht in die DB einfügen - sehe ich das irgendwo?

**Comment by abrain** [comment]
Das Einfügen in die Datenbank erfolgt über eine Funktion von WordPress selbst, und bei einem Fehler bekomme ich leider auch nicht mehr Informationen über das Problem zurück. Die wahrscheinlichste Ursache ist an dieser Stelle aber die Verwendung von Sonderzeichen. Wenn in der Datei exotische Zeichen enthalten sind, könnte es reichen, diese zu entfernen.

Das Problem kann aber auch durch ein ungeeignetes Encoding der Datei entstehen. In der Regel erwartet der Server eine Datei im Encoding UTF-8. Ältere Software (gerade unter Windows) verwendet gerne das Encoding Windows-1252 oder ISO-8859-1 (auch bekannt als Latin-1). Sofern sich das Encoding nicht beim Exportieren einstellen lässt, kann es im nachhinein mit Texteditoren wie [Notepad++](https://notepad-plus-plus.org/) verändert werden.

![VirtualBox_Win10_23_11_2020_14_22_15](https://user-images.githubusercontent.com/1263052/99967194-cbf3db80-2d97-11eb-8178-2119fc58b36b.png)

**Comment by benedikt5201** [comment]
Das war das Problem! - Wordpress ist mit der Kodierung nicht klar gekommen - habe es zu UTF-8 konvertiert, danach hat es funktioniert.

Danke!
