### ISSUE TITLE
Layoutprobleme mit dem Theme „ColorMag“

### ISSUE THREAD

**Issue by denis1994** [abrain/einsatzverwaltung#217]
Hallo,

Wir haben das Theme auf unsere Seite geändert und verwenden jetzt das Theme „ColorMag“. Leider gibt es Probleme mit der Darstellung von Einsatzberichte in der News Seite. Die werden nicht wie normale Beiträge angezeigt und somit geht das Layout kaputt. Siehe hier: https://www.cisp.lu/news/

Was kann ich da machen damit das ordentlich angezeigt wird ? Vielen Dank!

**Comment by abrain** [comment]
Hi,

das Grundproblem und der Lösungsansatz sind in diesem Artikel beschrieben: https://einsatzverwaltung.abrain.de/2018/12/wenn-sich-einsatzberichte-nicht-dem-design-der-seite-anpassen/

Ich habe mal schnell reingeschaut, bei dem Theme sind es auf jeden Fall mehrere Regeln, die angepasst werden müssen.

**Comment by denis1994** [comment]
Vielen Dank für den Link! Das hat mir geholfen, jetzt sieht es besser aus ;)
