### ISSUE TITLE
Fehler bei Erstellen von Beiträgen aller Art durch Einsatzverwaltung

### ISSUE THREAD

**Issue by abelabelpaul** [abrain/einsatzverwaltung#219]
`Fatal error: Uncaught TypeError: Argument 4 passed to abrain\Einsatzverwaltung\ReportNumberController::onPostMetaChanged() must be of the type string, array given, called in /homepages/24/d843787311/htdocs/clickandbuilds/FFObertiefenbach/wp-includes/class-wp-hook.php on line 292 and defined in /homepages/24/d843787311/htdocs/clickandbuilds/FFObertiefenbach/wp-content/plugins/einsatzverwaltung/ReportNumberController.php:49 Stack trace: #0 /homepages/24/d843787311/htdocs/clickandbuilds/FFObertiefenbach/wp-includes/class-wp-hook.php(292): abrain\Einsatzverwaltung\ReportNumberController->onPostMetaChanged(10691, 2918, '_tribe_modified...', Array) #1 /homepages/24/d843787311/htdocs/clickandbuilds/FFObertiefenbach/wp-includes/class-wp-hook.php(316): WP_Hook->apply_filters(NULL, Array) #2 /homepages/24/d843787311/htdocs/clickandbuilds/FFObertiefenbach/wp-includes/plugin.php(484): WP_Hook->do_action(Array) #3 /homepages/24/d843787311/htdocs/clickandbuilds/FFObertiefenbach/wp-includes/meta.php(133): do_action('added_post_meta', 10 in /homepages/24/d843787311/htdocs/clickandbuilds/FFObertiefenbach/wp-content/plugins/einsatzverwaltung/ReportNumberController.php on line 49`

Ich nutze das Avada Theme und diverse Plugins darunter Einsatzverwaltung seit dem Update tritt bei mir dieser Fehler auf sobald  ich eine Seite, Veranstaltung oder sonstiges erstellen möchte. Ich bin neu hier auf Github und hoffe alles nötige reingeschrieben zu haben.

Ich hoffe mir kann jemand weiterhelfen, danke schonmal im Vorraus.

**Comment by abrain** [comment]
Hi, danke für den Fehlerbericht. Die detaillierte Fehlermeldung war super hilfreich, den Fehler konnte ich finden und beheben.

Ein Update mit der Behebung kommt in Kürze, ich prüfe noch schnell, ob sich weitere ähnliche Fehler versteckt haben.

**Comment by abelabelpaul** [comment]
Habe auch gerade Testweise mal auf die Version downgegraded und da klappt alles. Vielen Dank für die schnelle Hilfe und ein super Plugin.
