### ISSUE TITLE
Einheiten und Fahrzeuge nur in englischer Sprache

### ISSUE THREAD

**Issue by LukasPesch** [abrain/einsatzverwaltung#221]
Nach Fehlerbehebung: Einheiten ohne Fahrzeuge konnten im Editor nicht ausgewählt werden (Update 1.9.2) werden Einheiten und Fahrzeuge im fertigen Einsatzbericht als "Units and Vehicles" dargestellt.
![Screenshot 2021-03-25 182339](https://user-images.githubusercontent.com/65612860/112516143-43ae3300-8d97-11eb-95a5-fd20190111f8.png)

**Comment by abrain** [comment]
Hi, danke für die Meldung. Kannst du mal bei den Aktualisierungen nachsehen, da müsste noch ein Update für die Übersetzung ausstehen?

**Comment by LukasPesch** [comment]
Vielen Dank für die schnelle Antwort, dadurch wurde es gelöst!
