### ISSUE TITLE
Moin, ich schon wieder. Liegt es an deinem Plugin dass ich bestimmte löcke nicht in den Text einfügen kann?

### ISSUE THREAD

**Issue by abelabelpaul** [abrain/einsatzverwaltung#222]

**Comment by abelabelpaul** [comment]
Ich nutzte Avada bei Wordpress und würde gerne eine andere Bildergalerie nutzen als von Wordpress. Diese ist bei Avada dabei nur kann ich die bei den Einsatzberichten nicht einfügen. Bei normalen Berichten schon. Brauchst du noch mehrt Infos?

Vielen Dank im Voraus

**Comment by abrain** [comment]
Wird der Block beim Bearbeiten von Einsatzberichten erst gar nicht angezeigt oder gibt es ein Problem beim Einfügen bzw. Ansehen?

**Comment by abelabelpaul** [comment]
Der Block wird gar nicht angezeigt.
![image](https://user-images.githubusercontent.com/81163670/112523029-97704a80-8d9e-11eb-8a59-83eb0dbf26c9.png)

Ich habe nur die Standard Blöcke zur Auswahl

**Comment by abrain** [comment]
Hmm, mit Avada habe ich keine eigenen Erfahrungen. Bringt es etwas, wenn du nach [dieser Anleitung](https://theme-fusion.com/documentation/avada/avada-builder/avada-builder-custom-post-types/) die Einsatzberichte aktivierst?

**Comment by abelabelpaul** [comment]
Ja über einen kleinen Workaround mit dem Avada Builder klappt das, sorry dass ich dachte dass das Problem lan dem Plugin liegt.

**Comment by abrain** [comment]
Kein Problem. Es kann auch durchaus mal Dinge geben, die vom Plugin verursacht werden. Gerade im Zusammenspiel mit kostenpflichtigen Plugins und Themes habe ich nicht die Möglichkeit alles zu testen.

**Comment by abelabelpaul** [comment]
Trotzdem vielen Dank für deine schnelle Hilfe, ich werde dir bald den Link für deine Referenzen schicken sobald unsere Website online geht.
