### ISSUE TITLE
Einsatznummern Trennzeichen hat keine Funktion

### ISSUE THREAD

**Issue by KiwiKilian** [abrain/einsatzverwaltung#224]
Die Funktion Trennzeichen für die Einsatznummern (#65) bleibt bei unserer Instanz scheinbar ohne Wirkung. Ich habe auf Bindestrich eingestellt, in der WP Admin Ansicht in Liste wie auch beim Bearbeiten bleiben aber weiterhin die alten Einsatznummern.

Plugin v1.9.4
WP v5.7.1

![Bildschirmfoto 2021-05-02 um 21 36 45](https://user-images.githubusercontent.com/18724559/116825245-ad87dc80-ab8e-11eb-92a4-a8ea8050a96f.png)
![Bildschirmfoto 2021-05-02 um 21 36 55](https://user-images.githubusercontent.com/18724559/116825247-aeb90980-ab8e-11eb-8a10-0b2a71924e6d.png)

**Comment by abrain** [comment]
Wird das eingestellte Format verwendet, wenn du einen neuen Bericht veröffentlichst?

**Comment by KiwiKilian** [comment]
Das klappt tatsächlich.

![Bildschirmfoto 2021-05-03 um 11 55 33](https://user-images.githubusercontent.com/18724559/116863379-85d45b00-ac06-11eb-9a6c-269231ea81ef.png)

**Comment by abrain** [comment]
Nein, das soll so nicht sein. Wenn das Format der Einsatznummer geändert, oder die Automatik eingeschaltet wird, werden alle bestehenden Einsatznummern gemäß dem neuen Format überschrieben. Da scheint es aber tatsächlich einen Bug zu geben, wenn die Automatik und das Format gleichzeitig geändert werden.

Wenn du jetzt eine kleine Änderung im Format (z. B. auf Schrägstrich umstellen) vornimmst, sollten auch die bestehenden Einsatznummern geändert werden. Danach kannst du die Einstellung wieder zurück ändern und dann sollte es passen.

**Comment by KiwiKilian** [comment]
Vielen Dank! Der Workaround hat schon mal geklappt.

> Da scheint es aber tatsächlich einen Bug zu geben, wenn die Automatik und das Format gleichzeitig geändert werden.

Die Automatik war vorher bei uns bereits aktiviert. Ich habe nur das Trennzeichen von "Keines (Standard)" auf "Bindestrich" gewechselt.
