### ISSUE TITLE
Fahrzeuge außer Dienst nicht mehr der Einheit zugeordnet

### ISSUE THREAD

**Issue by LukasPesch** [abrain/einsatzverwaltung#226]
Wir haben vor kürzen eines unserer Fahrzeuge außer Dienst gestellt. In den alten Berichten wird dieses nicht mehr der Ursprünglichen Einheit zugewiesen,
Eventuell wäre es schöner das Fahrzeug weiterhin der Einheit unterzuordnen und einfach nur mit einem "a.D." oder ähnlichem zu Kennzeichen.
Siehe dazu: https://www.ff-wittlich.de/einsatzberichte/auslaufende-betriebsstoffe-13/ (Es handelt sich hierbei um das Fahrzeug MZF 1 (Standort 2))

**Comment by abrain** [comment]
Ich habe mir den Code dazu gerade mal angesehen. Eine Unterscheidung nach in/außer Dienst sollte an der Stelle nicht greifen. Auch habe ich bei einem Test ein bereits einem Einsatzbericht und einer Einheit zugeordnetes Fahrzeug außer Dienst genommen. Im Einsatzbericht wird es weiter unter der Einheit angezeigt wie zuvor.

Wird im Adminbereich bei den Fahrzeugen noch eine Einheit für dieses Fahrzeug angezeigt?

**Comment by LukasPesch** [comment]
Das Fahrzeug war tatsächlich keiner Einheit mehr zugeordnet. Scheinbar wurde nach dem "außer Dienst stellen" des Fahrzeuges aus irgendeinem Grund die Zuordnung des Fahrzeuges zur Einheit entfernt.

**Comment by abrain** [comment]
Ok, dann hat sich das erst mal geklärt 😀 Einen Bug konnte ich nicht erkennen, also auch nicht, dass beim Außerdienststellen automatisch die Zuordnung zur Einheit entfernt wurde.

Ist der Vorschlag mit der Markierung _a.D._ dann noch aktuell? Genau genommen waren die Fahrzeuge bei den Berichten, in denen sie angezeigt werden, noch nicht außer Dienst.

**Comment by LukasPesch** [comment]
Okay alles klar danke!

Das ist richtig und macht die Markierung somit eigentlich unnötig.
