### ISSUE TITLE
Kritischer Fehler beim Einsatzberichte importieren

### ISSUE THREAD

**Issue by T-Bone90** [abrain/einsatzverwaltung#229]
Guten Abend,

ich bin aktuell dabei, eventuell von Joomla auf Wordpress umzusteigen und wollte gerne meine Einsatzberichte von der Einsatzkomponente mitnehmen in eurer Wordpress Plugin. Das ist natürlich etwas Arbeit. Ich wollte in der Joomla Datenbank einfach die Einsatzberichte als csv exportieren und dann importieren.

Bekomme aber jedes mal den Fehler:

"
Analyse

Es gab einen kritischen Fehler auf deiner Website. Bitte überprüfe den Posteingang deiner Website-Administrator-E-Mail-Adresse für weitere Anweisungen.

Erfahre mehr über die Problembehandlung in WordPress.
"

Kann machen was ich will. Selbst, wenn ich eine leere Datei importieren will. Oder wenn ich mit eurem Tool exportiere (leere Datei nur Überschrift) und dann direkt wieder importiere. Gleicher Fehler.
Wordpress 5.8 mit PHP 7.4

Gibt es eventuell auch eine einfache Variante, von der Einsatzkomponente zu importieren?

**Comment by abrain** [comment]
Hi, danke für den Fehlerbericht.

> Bitte überprüfe den Posteingang deiner Website-Administrator-E-Mail-Adresse für weitere Anweisungen.

Kam da eine Email an? Dort müssten weitere Details zum Fehler stehen. Besonders interessant wäre, in welcher Datei und welcher Zeile der Fehler verursacht wurde und welche Art von Fehler das war.

> Gibt es eventuell auch eine einfache Variante, von der Einsatzkomponente zu importieren?

Derzeit gibt es nichts speziell für die EInsatzkomponente. Da sich diese ständig weiterentwickelt, müsste auch der Import laufend angepasst werden. Dafür fehlt aktuell die Zeit.

**Comment by T-Bone90** [comment]
Ja stimmt hier ist der Fehlerbericht in der Email. Ich habe mal die Domain und Server mit x versehen.

Fehler-Details
==============
Ein Fehler vom Typ E_ERROR wurde in der Zeile 261 der Datei /www/htdocs/xxxxxxxxx/wp-content/plugins/einsatzverwaltung/Import/Tool.php verursacht. Fehlermeldung: Uncaught TypeError: implode(): Argument #2 ($array) must be of type ?array, string given in /www/htdocs/xxxxxxxxx/wp-content/plugins/einsatzverwaltung/Import/Tool.php:261
Stack trace:
#0 /www/htdocs/xxxxxxxxx/wp-content/plugins/einsatzverwaltung/Import/Tool.php(261): implode(Array, ', ')
#1 /www/htdocs/xxxxxxxxx/wp-content/plugins/einsatzverwaltung/Import/Tool.php(191): abrain\Einsatzverwaltung\Import\Tool->analysisPage()
#2 /www/htdocs/xxxxxxxxx/wp-includes/class-wp-hook.php(303): abrain\Einsatzverwaltung\Import\Tool->renderToolPage('')
#3 /www/htdocs/xxxxxxxxx/wp-includes/class-wp-hook.php(327): WP_Hook->apply_filters('', Array)
#4 /www/htdocs/xxxxxxxxx/wp-includes/plugin.php(470): WP_Hook->do_action(Array)
#5 /www/htdocs/xxxxxxxxx/wp-admin/admin.php(259): do_action('tools_page_eins...')
#6 /www/htdocs/xxxxxxxxx/wp-admin/tools.php(40): require_once('/www/htdocs/w00...')
#7 {main}
  thrown

**Comment by abrain** [comment]
Danke, das hat sehr geholfen. 👍🏻 Ich habe den Fehler lokalisiert und ein Fix kommt in Kürze.
