### ISSUE TITLE
Fragen zu Archiven

### ISSUE THREAD

**Issue by JanHeppner** [abrain/einsatzverwaltung#230]
Hallo Andreas,

Ich habe gleich mehrere Fragen:

1. Am 31.08.2021 hat unsere Leitstelle auf einen neuen Leitstellenrechner geupgradet. Seitdem sind die Einsatzmeldungen andere. Gibt es die Möglichkeit, dass wir ein Archiv erstellen, dass nicht ganz 2021 umfasst, sondern eins mit 2021 bis einschließlich August und eins ab 09 bis Ende 2021? Da sich teilweise Stichworte überschneiden kann ich nicht ein Archiv nur für die neuen Stichwörter erstellen..
2. Neuerdings haben wir einen anderen Fehler. Wenn man einen Einsatzbericht öffnet, erscheint die Fehlermeldung "Es gab einen kritischen Fehler auf deiner Website." Kannst du uns da helfen?
3. Kann man die Felder "Einsatzart" und "Einsatzmeldung" umbenennen? Die heißen seit der Umstellung des LST-Rechners auch anders.. 

Vielen Dank für deine Hilfe auch jetzt schon!

Gruß
Jan Heppner

Link zum Archiv: https://ff-dorsten.de/einsatzberichte-feuerwehr-dorsten/#
Plugin: 1.9.7, WordPress: 5.8.1, PHP: 7.4.23

**Comment by abrain** [comment]
>  Gibt es die Möglichkeit, dass wir ein Archiv erstellen, dass nicht ganz 2021 umfasst, sondern eins mit 2021 bis einschließlich August und eins ab 09 bis Ende 2021? Da sich teilweise Stichworte überschneiden kann ich nicht ein Archiv nur für die neuen Stichwörter erstellen..

Falls du das Archiv unter /einsatzberichte/ bzw. /einsatzberichte/2021/ meinst, dann leider nein. Das ist nur auf eine jährliche Unterteilung ausgelegt. Oder meinstest du die Tabelle (Einsatzliste)?

> Neuerdings haben wir einen anderen Fehler. Wenn man einen Einsatzbericht öffnet, erscheint die Fehlermeldung "Es gab einen kritischen Fehler auf deiner Website." Kannst du uns da helfen?

Nur mit dieser Fehlermeldung leider noch nicht. Bekommst du bzw. jemand mit Administratorkonto eine Email mit Details? Könnt ihr beim Webhoster in ein Error-Logfile schauen?

> Kann man die Felder "Einsatzart" und "Einsatzmeldung" umbenennen? Die heißen seit der Umstellung des LST-Rechners auch anders..

Zu dem Thema hast du [im Support-Forum ja schon eine Antwort bekommen](https://de.wordpress.org/support/topic/css-code-textbaustein-ueberschreiben/#post-114834). Ich persönlich hätte es leicht anders gelöst, betrifft aber speziell nur die Einsatzliste: https://gist.github.com/abrain/c92b89c6c32cfdb2ff6375147fb669ae (diese Datei ist ein eigenes, sehr kleines Plugin. Kannst du einfach in /wp-content/plugins/ legen und wie jedes andere Plugin aktivieren).

**Comment by JanHeppner** [comment]
> Falls du das Archiv unter /einsatzberichte/ bzw. /einsatzberichte/2021/ meinst, dann leider nein. Das ist nur auf eine jährliche Unterteilung ausgelegt. Oder meinstest du die Tabelle (Einsatzliste)?
Wenn ich quasi eine Seite anlege und durch den Shortcode eine Einsatzliste generieren lasse, dann möchte ich nur alle Einsätze ab dem 01.09.2021 sehen bis zum 31.12.2021 dann.


> Nur mit dieser Fehlermeldung leider noch nicht. Bekommst du bzw. jemand mit Administratorkonto eine Email mit Details? Könnt ihr beim Webhoster in ein Error-Logfile schauen?
Eine E-Mail erhalte ich leider nicht. Ich glaube das müsste ein Log-Eintrag sein, wenn ich einen verlinken Einsatz anklicke: "AH01276: Cannot serve directory /usr/www/users/ffidor/main/wp-admin/css/: No matching DirectoryIndex (index.html,index.htm,index.shtml,index.cgi,index.php3,index.php4,index.php,index.wml,index.asp,index.jsp,Index.jsp,Index.html,Index.htm,home.html,home.htm,Home.htm,Home.html,home.jsp,welcome.html,default.html,default.htm,default.php,default.jsp,Default.htm,Default.html) found, and server-generated directory index forbidden by Options directive, referer: binance.com"



> Zu dem Thema hast du [im Support-Forum ja schon eine Antwort bekommen](https://de.wordpress.org/support/topic/css-code-textbaustein-ueberschreiben/#post-114834). Ich persönlich hätte es leicht anders gelöst, betrifft aber speziell nur die Einsatzliste: https://gist.github.com/abrain/c92b89c6c32cfdb2ff6375147fb669ae (diese Datei ist ein eigenes, sehr kleines Plugin. Kannst du einfach in /wp-content/plugins/ legen und wie jedes andere Plugin aktivieren).

Perfekt, danke! Das werde ich nutzen! ;-)


Vielen Dank schon einmal für deine Hilfe!

**Comment by JanHeppner** [comment]
Ich habe deinem Mini-Plugin noch eine zweite Wortänderung hinzugefügt. Von Einsatzmeldung zu Einsatzstichwort. Nun schiebt sich die Uhrzeit in eine zweite Ziele. Kann ich das beheben?

**Comment by abrain** [comment]
> Wenn ich quasi eine Seite anlege und durch den Shortcode eine Einsatzliste generieren lasse, dann möchte ich nur alle Einsätze ab dem 01.09.2021 sehen bis zum 31.12.2021 dann.

Die Einsatzliste ist ebenso nur darauf ausgelegt, nach Jahren zu filtern. Das Ganze jetzt noch um einen von-bis-Filter zu erweitern, würde den Shortcode noch komplexer machen. Wenn diese zeitliche Einschränkung nur auf einer bestimmten Seite greifen soll, dann *müsste* das ebenso über einen Codeschnipsel speziell für eure Webseite lösbar sein. Ich würde ungern für einen Einzelfall den Shortcode umbauen.

> Ich glaube das müsste ein Log-Eintrag sein, wenn ich einen verlinken Einsatz anklicke: [...]

Der Fehler sieht mir nicht so aus, als hätte er etwas mit dem Plugin zu tun. Stutzig macht mich der Referrer am Ende: Binance ist eine Handelsplattform für Bitcoin. Ich hoffe, ihr habt euch keine Malware eingetreten.

**Comment by JanHeppner** [comment]
Hallo Andreas,

es war viel los, sodass das Thema leider auf der Strecke geblieben ist.

> Die Einsatzliste ist ebenso nur darauf ausgelegt, nach Jahren zu filtern. Das Ganze jetzt noch um einen von-bis-Filter zu erweitern, würde den Shortcode noch komplexer machen. Wenn diese zeitliche Einschränkung nur auf einer bestimmten Seite greifen soll, dann _müsste_ das ebenso über einen Codeschnipsel speziell für eure Webseite lösbar sein. Ich würde ungern für einen Einzelfall den Shortcode umbauen.

Es soll quasi nur ein bestimmtes Archiv auf einer bestimmten Seite sein. Also wenn du da mit einem Codeschnipsel uns helfen könntest, wäre super!
 
> Der Fehler sieht mir nicht so aus, als hätte er etwas mit dem Plugin zu tun. Stutzig macht mich der Referrer am Ende: Binance ist eine Handelsplattform für Bitcoin. Ich hoffe, ihr habt euch keine Malware eingetreten.

Das Problem habe ich gelöst, Danke!

**Comment by abrain** [comment]
Hallo Jan, hat das geholfen?

**Comment by JanHeppner** [comment]
Hallo Andreas,

wie immer. Hat geholfen ;-)! Vielen Dank :-).

Gruß Jan

**Comment by abrain** [comment]
Sehr gut :) 👍🏻
