### ISSUE TITLE
Fehler beim ersten Ändern der Einsatzberichtekategorie

### ISSUE THREAD

**Issue by abrain** [abrain/einsatzverwaltung#232]
Bei einer frischen Installation kann das Setzen der Kategorie, in der Einsatzberichte erscheinen sollen, einen Fehler verursachen. Das betrifft Version 1.9.0 und neuer.

Der Workaround wäre, in der Tabelle *_options einen Eintrag mit option_name = "einsatzvw_category" und option_value = "-1" hinzuzufügen.

**Comment by T-Bone90** [comment]
Danke für die Info!

Habe weitere Fehler entdeckt. Ich habe gerade ein paar Einsätze neu angelegt, da es Fehler gab und ich dachte durch neu anlegen diese zu entfernen. Direkt nach dem Neu anlegen kommen die gleichen Fehler.

"
Es gab einen kritischen Fehler auf deiner Website.

Erfahre mehr über die Problembehandlung in WordPress.
"
Manche Einsätze gehen komischerweise, obwohl es keine unterschiede gibt.

Das mit der Kategorie kann ich auch bestätigen. Wollte alle Einsätze auf einmal einer Kategorie zuordnen und zerschieße mir damit alles.

**Comment by abrain** [comment]
Werden die neuen Einsätze gespeichert? Bekommst du per Mail Details zum Fehler?

Das mit der Kategorie möchte ich so abändern, dass die Einstellung nur für neue Einsätze gilt (so macht das WordPress für die Beiträge auch). Eine rückwirkende Änderung der Kategorie aller Einsatzberichte soll dann nicht mehr automatisch passieren.

Eine massenhafte Änderung der Kategorie kann auch über die _Mehrfachaktionen_ in der Auflistung aller Einsatzberichte im Adminbereich vorgenommen werden. Dazu kann es sinnvoll sein, rechts oben unter _Ansicht anpassen_ die Anzahl der Berichte pro Seite zu erhöhen, um nicht zu viele Seiten durchblättern zu müssen.

![Bildschirmfoto 2021-11-03 um 12 51 53](https://user-images.githubusercontent.com/1263052/140055330-04618b5e-dbbb-46f1-8a8c-1f3e8fc2c4a3.png)

![Bildschirmfoto am 2021-11-03 um 12 54 52](https://user-images.githubusercontent.com/1263052/140055607-8dcfa28a-97e6-425b-95ae-dcbf4220d9ef.png)

**Comment by T-Bone90** [comment]
Die Fehler sind mittlerweile weg. Keine Ahnung, was ich gemacht habe. Mail habe ich leider keine erhalten.
Ich hatte einfach weiter neue Einsätze angelegt und es geht plötzlich alles.

Bezüglich der Kategorie war gerade das, was ich ändern wollte. Ich komme von Joomla und wollte bei der Umstellung jetzt alle Einsätze einer Kategorie zuweisen. Ob das sinnvoll ist, weiß ich nicht...was meinst du?
Normal werden Einsatzberichte ja ohne Kategorie bzw mit "Allgemein" angelegt.  Im Prinzip reicht mir das aber weiß ja nicht, ob man später mal die Filterung nach "Einsatzkategorie" braucht.
Auf jeden Fall wollte ich über die Mehrfachauswahl alle Einsätze in die neue Kategorie schieben und habe mir damit sehr viele Fehler ins Boot geholt. Es kam immer wieder der gleiche Fehler wie oben. Deshalb habe ich es jetzt nicht nochmal probiert, da ich nicht alles zerstören will.

**Comment by abrain** [comment]
Das mit der Kategorie ist in meinen Augen nicht unbedingt nötig. In meiner Feuerwehr verwenden wir das Feature zum Beispiel nicht. Eigentlich braucht es das nur, wenn man die Einsatzberichte mit den Beiträgen vermischen möchte.

**Comment by T-Bone90** [comment]
Danke für die Info!
Also ich fand die Idee, besondere Einsätze zu markieren und diese dann zwischen den Beiträgen erscheinen zu lassen, eigentlich recht gut. Aber irgendwie habe ich es nicht hinbekommen.

Sprich ich lasse dann einfach alle Einsätze so, wie sie sind und wenn ich doch mal einen zwischen den Beiträgen will dann setze ich den Hacken und wähle die eine Kategorie?
Vermutlich lag es daran. Ich dachte Haken setzen (Besonderer Einsatz) und fertig. Aber ich habe es auf Standardkategorie (Aktuell) gelassen.

**Comment by abrain** [comment]
Die Einstellungen zu dem Thema sind nicht ganz ideal, deshalb habe ich jetzt einen eigenen Issue dafür angelegt. Aktuelles Verhalten ist, dass wenn eine Kategorie für die Einsatzberichte eingestellt wurde, alle Einsatzberichte zwangsweise dieser Kategorie zugeordnet werden.

Wenn das mit der Kategorie nicht relevant ist, und die besonderen Einsatzberichte nur zwischen den Beiträgen auf der Startseite erscheinen sollen, müsste diese Einstellung funktionieren:
![Bildschirmfoto 2021-11-10 um 16 11 06](https://user-images.githubusercontent.com/1263052/141141712-8fe416bd-1479-49e0-acb0-2903524fac66.png)

Dann wäre es wirklich nur Haken "Besonderer Einsatz" setzen und gut.
