### ISSUE TITLE
Rechteverwaltung

### ISSUE THREAD

**Issue by T-Bone90** [abrain/einsatzverwaltung#233]
Hallo zusammen,
wir haben vor kurzem auf das Plugin umgestellt und sind sehr zufrieden.
Nun gibt es eine neue Anforderung. Wir möchten gerne die Rechteverwaltung etwas "besser" regeln können. Haben uns dazu das Plugin "User Role Editor" und eine neue Rolle erschaffen. Wir haben einen Mitarbeiter, der nur Einsatzberichte machen soll. Bedingung ist, dass er alte vom Admin nicht ändern oder löschen kann, sondern nur seine eigenen Bearbeiten kann bis zur Veröffentlichung.
Das gleiche bei den Alarmierungsarten und Einheiten.

Problem ist, dass das so nicht geht. Ich hake in der Einsatzverwaltung die neue Rolle bei Berechtigung an und plötzlich kann er alles, obwohl ich ihm über das Rechte Plugin die nötigen Rechte der Einsatzverwaltung genommen habe.

Gibt es dafür eine Lösung?

Vielen Dank im Voraus.

**Comment by abrain** [comment]
Wenn die Rechte über den User Role Editor vergeben werden, dann sollte die neue Rolle nicht in den Einstellungen angehakt werden. Durch den Haken erhält diese Rolle alle Rechte zur Laufzeit. Die Möglichkeit in den Einstellungen ist für Anwender gedacht, die nicht URE oder ähnliche Plugins verwenden.

Das Problem hat sich in gewisser Weise auch schon gelöst, weil ich das kürzlich umgebaut habe (kommt in wenigen Tagen mit einem Update). Die Einsatzverwaltung bringt jetzt eigene Rollen mit, die Haken in den Einstellungen entfallen. Die neuen Rollen funktionieren analog zu Mitarbeiter, Autor und Redakteur, jedoch speziell für Einsatzberichte. Man könnte dem Mitarbeiter also die Rolle _Einsatzberichte-Mitarbeiter_ zuweisen und er könnte nur Berichte schreiben, und zur Veröffentlichung markieren. Veröffentlichte Berichte und die von anderen Autoren sind nicht bearbeitbar.

Was Alarmierungsarten, Einheiten etc. angeht, sind die Verwaltungsrechte aktuell noch an das Bearbeiten von Einsatzberichten gekoppelt. Das dürften also auch die Mitarbeiter. Das soll auch noch aufgetrennt werden, aber erst wollte ich mal sehen, dass die Umstellung auf die Rollen funktioniert.

**Comment by T-Bone90** [comment]
Super Danke! Da warte ich mal auf das Update.
Leider hatte es nicht funktioniert, den Haken in den Einstellungen der Einsatzverwaltung bei der Rolle zu entfernen und die Rechte dann per User Role Editor zu geben. Danach hatte der jeweilige User keine Einsatzberichte Spalte auf der Linken Seite.

**Comment by abrain** [comment]
Er bräuchte die Rechte `edit_einsatzberichte` und `delete_einsatzberichte`. Generell zum Einloggen ist das Recht `read` nötig, aber das muss nur gesetzt werden, wenn der Benutzer sonst keine Rollen (mit diesem Recht) hat.

**Comment by T-Bone90** [comment]
Ah ok danke das hilft! Damit komme ich erstmal bis zum Update klar super. Danke dir!

**Comment by abrain** [comment]
Da gibt es eigene Plugins dafür, ich habe aber aktuell keines im Einsatz. Könnte also keines empfehlen.

**Comment by abrain** [comment]
Das Update mit den Rollen ist draußen: https://einsatzverwaltung.org/2021/11/version-1-10-0/
