### ISSUE TITLE
Problem beim erstellen eines Einsatzberichtes

### ISSUE THREAD

**Issue by christofschloegl** [abrain/einsatzverwaltung#238]
Hallo in die Runde, ich habe folgendes Problem beim erstellen eines Posts:

Uncaught TypeError: Argument 3 passed to abrain\Einsatzverwaltung\Data::onTransitionPostStatus() must be an instance of WP_Post, null given, called in /WWWROOT/122185/htdocs/wp-includes/class-wp-hook.php on line 303 and defined in /WWWROOT/122185/htdocs/wp-content/plugins/einsatzverwaltung/Data.php:257 Stack trace: #0 /WWWROOT/122185/htdocs/wp-includes/class-wp-hook.php(303): abrain\Einsatzverwaltung\Data->onTransitionPostStatus('auto-draft', 'new', NULL) #1 /WWWROOT/122185/htdocs/wp-includes/class-wp-hook.php(327): WP_Hook->apply_filters(NULL, Array) #2 /WWWROOT/122185/htdocs/wp-includes/plugin.php(470): WP_Hook->do_action(Array) #3 /WWWROOT/122185/htdocs/wp-includes/post.php(5098): do_action('transition_post...', 'auto-draft', 'new', NULL) #4 /WWWROOT/122185/htdocs/wp-includes/post.php(4368): wp_transition_post_status('auto-draft', 'new', NULL) #5 /WWWROOT/122185/htdocs/wp-admin/includes/post.php(694): wp_insert_post(Array, false, false) #6 /WWWROOT/122185/htdocs/wp-admin/post-new.php(66): get_default_post_ in /WWWROOT/122185/htdocs/wp-content/plugins/einsatzverwaltung/Data.php on line 257 

Leider kann ich zurzeit keinen Beitrag erstellen, habt ihr eine Idee, an was dies liegt?

**Comment by christofschloegl** [comment]
Ich denke es liegt an einem anderen Problem, und nicht am Plugin, hiermit schließe ich das Ticket.

**Comment by abrain** [comment]
Hallo, ja und nein. Die Ursache liegt sehr wahrscheinlich nicht im Plugin. Sichtbar wird das Problem jedoch dadurch, dass das Plugin an manchen Stellen eine relativ strikte Prüfung der Datentypen macht. Es kann gut sein, dass ein anderes Plugin hier einen Fehler hat.

Mit dem Plugin [Health Check & Troubleshooting](https://wordpress.org/plugins/health-check/) kann man für den eigenen Benutzer eine Debug-Session starten, während für die anderen Besucher die Seite normal weiter funktioniert. Damit könnte man das verantwortliche Plugin oder (auch auch Theme) eingrenzen.

**Comment by christofschloegl** [comment]
Das Problem war das Einspielen eines Backups (wegen eines Angriffs auf die Homepage). Nach dem erneuten Setzen von Auto increment id auf wp posts ging alles wieder ;)

**Comment by abrain** [comment]
Ah, wieder was gelernt :) 👍🏻
