### ISSUE TITLE
Uhrzeit Tagesform entfernen

### ISSUE THREAD

**Issue by CBSERV** [abrain/einsatzverwaltung#239]
Hallo,

wie bekomme ich denn im Einsatzbericht das AM/PM weg?

lg

**Comment by abrain** [comment]
Das Format für Datum und Uhrzeit wird aus den globalen WordPress-Einstellungen gezogen. Diese sind unter Einstellungen -> Allgemein zu finden. Ansonsten kann auch noch die eingestellte Spache einen Einfluss auf das Format haben. Die ist ebenso in den allgemeinen Einstellungen zu finden.

**Comment by CBSERV** [comment]
ah jo lag an der sprache..
