### ISSUE TITLE
Fehler FE2 Anbindung

### ISSUE THREAD

**Issue by Manuel1607** [abrain/einsatzverwaltung#241]
Hallo, 
kann mir jemand helfen, ich habe auch die 2.24 installiert und bei mir geht es leider nicht. Ich habe dem Nutzer auch die Rechte Incident Reports API zugewiesen und leider kommt bei mit die Fehlermeldung, Der Einsatz konnte nicht angelegt werden (Du bist leider nicht berechtigt, diese Aktion durchzuführen.)

Jemand ne Idee? Habe ich was vergessen?

_Originally posted by @Manuel1607 in https://github.com/abrain/einsatzverwaltung/issues/240#issuecomment-1003555441_

**Comment by Manuel1607** [comment]
Folgendes sagt die Log Datei im FE2

Neuer Eingegangener Alarm

Typ: MANUAL

Externe ID: null

Key: "pluginmessage" Value: ""

Key: "keyword_description" Value: "test"

Key: "alarmType" Value: "MANUAL"

Key: "alarmState" Value: "NEW"

Key: "address" Value: "testeinheit_datei"

Key: "withStatistic" Value: "true"

Key: "keyword" Value: "test"

[00015]

01.01.2022 - 14:31:10.124 INFO |00015| [00015 - 15] AlarmPool - Neuer eingehender Alarm für "testeinheit_datei"
01.01.2022 - 14:31:10.125 INFO || [00015 - 15] AlarmPool - Anzahl aktiver Alarmabläufe: 1
01.01.2022 - 14:31:10.126 INFO |00015| [pool-15-thread-10] PipelineController - Bereite Ausführung der Pipeline für 'testeinheit_datei' vor
01.01.2022 - 14:31:10.126 INFO || [pool-15-thread-10] AlarmPool - Prüfe auf Doppelalarm...
01.01.2022 - 14:31:10.127 INFO |00015| [pool-15-thread-10] AlarmPool - Alarm für 'testeinheit_datei' wird von der Doppelalarm-Überprüfung ausgeschlossen
01.01.2022 - 14:31:10.131 INFO |00015| [pool-15-thread-10] AAOController - Alarmstichwort bereits vorhanden: test
01.01.2022 - 14:31:10.132 INFO |00015| [pool-15-thread-10] AddressGenerator - Versuche Einsatz-Adresse zu berechnen aus Feld (Modus: [COORDINATES_DEZ, COORDINATES_HEX, COORDINATES_GK])...
01.01.2022 - 14:31:10.132 WARN |00015| [pool-15-thread-10] AddressGenerator - Keine Adresse im Modus COORDINATES_DEZ gefunden
01.01.2022 - 14:31:10.133 WARN |00015| [pool-15-thread-10] AddressGenerator - Keine Adresse im Modus COORDINATES_HEX gefunden
01.01.2022 - 14:31:10.134 WARN |00015| [pool-15-thread-10] AddressGenerator - Keine Adresse im Modus COORDINATES_GK gefunden
01.01.2022 - 14:31:10.134 INFO |00015| [pool-15-thread-10] AddressGenerator - Gefundene Adresse: null , null null
01.01.2022 - 14:31:10.140 INFO || [pool-14-thread-9] VehicleController - Alarm ist kein Status
01.01.2022 - 14:31:10.249 INFO || [pool-15-thread-10] OnlineServicesController - Keine gültige oder aktive Rückmeldegruppe gefunden
01.01.2022 - 14:31:10.259 INFO |00015| [pool-15-thread-10] PipelineController - Für die Einheit 'Testeinheit Datei' (testeinheit_datei) wurde keine Rückmeldung aktiviert
01.01.2022 - 14:31:10.261 INFO |00015| [pool-15-thread-10] PipelineController - Pipeline-Vorbereitung beendet für testeinheit_datei
01.01.2022 - 14:31:10.261 INFO |00015| [pool-36-thread-9] Pipeline - Pipeline gestartet für Einheit (testeinheit_datei)
01.01.2022 - 14:31:10.261 INFO || [pool-36-thread-9] Pipeline - Pipeline von Einheit (testeinheit_datei) wurde gestartet
01.01.2022 - 14:31:10.273 INFO |00015| [EinsatzverwaltungThread-174797] PluginController - PluginController mit Plugin de.alamos.fe2.plugin.einsatzverwaltung.Einsatzverwaltung (Admin0) wurde gestartet
01.01.2022 - 14:31:12.480 WARN || [EinsatzverwaltungThread-174797] EinsatzverwaltungRequestHandler - {"code":"rest_forbidden","message":"Du bist leider nicht berechtigt, diese Aktion durchzuf\u00fchren.","data":{"status":401}}
01.01.2022 - 14:31:12.491 INFO |00015| [EinsatzverwaltungThread-174797] PluginController - PluginController mit Plugin de.alamos.fe2.plugin.einsatzverwaltung.Einsatzverwaltung (Admin0) nach 2216 ms beendet
01.01.2022 - 14:31:12.493 ERROR |00015| [pool-36-thread-9] Pipeline - ERRNO#1 PluginController de.alamos.fe2.plugin.einsatzverwaltung.Einsatzverwaltung (Admin0) wird nach einem Fehler übersprungen
01.01.2022 - 14:31:12.655 INFO |00015| [pool-36-thread-9] Pipeline - Alarmabarbeitung beendet
01.01.2022 - 14:31:12.658 INFO || [pool-36-thread-9] Pipeline - Alarmablauf von Einheit (testeinheit_datei) wurde nach 00:00:02.396 beendet. Fehler aufgetreten: Ja. Warnungen: Nein
01.01.2022 - 14:31:12.685 INFO || [Thread-433] AlarmPool - Anzahl aktiver Alarmabläufe (nach Stopp): 0
01.01.2022 - 14:31:13.160 INFO || [qtp1114884286-9671] OnlineServicesController - Status: 200
01.01.2022 - 14:31:13.166 INFO || [qtp1114884286-9669] OnlineServicesController - Status: 200

**Comment by Manuel1607** [comment]
Fehler gefunden. 

Ich nutze dort ein Plugin Wordfence Security, das blockiert die Anfrage von FE2. Habe es deaktiviert und nun geht es..

**Comment by abrain** [comment]
Gut, dass sich das lösen ließ und danke für das Teilen der Lösung.

Das Security-Plugin würde ich nicht zwangsläufig komplett deaktivieren, es war ja vermutlich aus gutem Grund installiert. Von anderen Security-Plugins kenne ich, dass es dort eigene Einstellungen zur REST-API gibt. Vielleicht lässt sich dort auch etwas einstellen, damit es zusammen funktioniert.
