### ISSUE TITLE
Einstellung "Einsatzberichte zwischen WordPress-Beiträgen anzeigen" hat keine Auswirkung auf WPtouch

### ISSUE THREAD

**Issue by yot-g** [abrain/einsatzverwaltung#243]
Die Einstellung "Einsatzberichte zwischen den regulären WordPress-Beiträgen anzeigen" hat keine Auswirkung auf WPtouch (Plugin für eine mobile Ansicht, wenn das Desktop-Theme keine Mobilansicht hat). Wir nutzen ein Desktop-Template ohne Mobilansicht, hier werden im Blog alle Einsatzberichte korrekt ausgeblendet. In WPtouch kann ich leider nur Kategorien für die komplette mobile Seite ausblenden, nicht lediglich für die Startseite. Somit werden leider alle Einsatzberichte im Blog angezeigt.

**Comment by abrain** [comment]
Dass es keine Auswirkung hat, konnte ich so nicht nachvollziehen. Allerdings habe ich einen anderen Fehler gefunden, der soeben mit Version 1.10.2 behoben wurde. Falls WPtouch noch zum Einsatz kommt, bitte noch einmal testen, ob das Problem noch besteht.

**Comment by yot-g** [comment]
Leider habe ich deine Antwort damals nicht gesehen/erhalten ^^
Vor drei Wochen habe ich auf ein modernes Theme umgestellt, daher hat es sich erledigt. Bis zuletzt wurden aber die Einsatzberichte weiterhin zwischen den normalen Beiträgen angezeigt. Trotzdem danke fürs anschauen.
