### ISSUE TITLE
Einsatzbericht Anlegen Optionen Fehlen + Widget einbinden

### ISSUE THREAD

**Issue by TVettel** [abrain/einsatzverwaltung#245]
Hi, 
ich bin selbst in einer Freiwilligen Feuerwehr tätig und will eine neue Website erstellen. Dabei bin ich auf das richtig coole Addon gestoßen. Schonmal danke dafür.

Ich habe folgende 2 Fragen:
Mit welchem Shortcode kann ich folgende Ansicht erzeugen?
<img width="733" alt="Bildschirmfoto 2022-04-17 um 13 42 17" src="https://user-images.githubusercontent.com/73441411/163712930-2ab889ce-bdb0-4aa5-9917-488d870a5b4f.png">

Wenn ich einen Einsatz über die Einsatzbericht erstellen Funktion posten will, fehlen mir die Optionen, welche Fahrzeuge, Alarmierungsart usw.. Die Optionen wurden zuvor natürlich bereits angelegt.
Liegt das evtl an meiner Wordpress Version?

<img width="1440" alt="Bildschirmfoto 2022-04-15 um 10 54 00" src="https://user-images.githubusercontent.com/73441411/163550914-a61fde28-7f71-4d24-abf2-e45f6e934630.png">

**Comment by TVettel** [comment]
Hi, das Problem mit dem Einbinden ist fast gelöst. Das Problem saß vor dem Gerät :).
Meine Frage hierzu ist aktuell nur noch, mit welchem Shortcode kann ich genau diese Anzeige realisieren?
<img width="733" alt="Bildschirmfoto 2022-04-17 um 13 42 17" src="https://user-images.githubusercontent.com/73441411/163712905-1eb240a4-23cb-4d27-b552-711419a0b273.png">

**Comment by abrain** [comment]
Auf die Gefahr hin, dass das viel zu spät kommt. Die oben gezeigte Auflistung der Einsatzberichte mit Links zu den Jahreslisten lässt sich über folgende Anleitung realisieren: https://einsatzverwaltung.org/2017/12/das-jahresarchiv-als-tabelle-darstellen/

Ich werde mich aber auch nochmal damit befassen, wie das ohne Änderungen am Theme umgesetzt werden kann.
