### ISSUE TITLE
Feature Request: Alle Einsatznummern bei mehren Einsätzen in einem Bericht anzeigen

### ISSUE THREAD

**Issue by x2on** [abrain/einsatzverwaltung#283]
Es wäre super wenn man bei der Liste der Einsatzberichte und im Einsatzbericht die "von" - "bis" Einsatznummern anzeigen könnte bei mehreren Einsätzen in einem Bericht.

Also z.b . enthält der Einsatzbericht "2023/098" ingesamt 7 Einsätze:
Aktuell steht in der Liste
"2023/098" und der nächste Eintrag ist "2023/106"

Besser wäre wenn in der Liste z.b. "2023/098 - 105" stehen würde oder ähnliches.

**Comment by Mululu** [comment]
Das war jemand bereits schneller 😉 

Würde das Feature ebenfalls befürworten! Wir nutzen zwar die umgekehrte Anzeige aber im Prinzip das gleiche:

Beispiel 4 Einsätze in einem Bericht

Aktuell: 04/2024 --> nächster Einsatz 08/2024
Wunsch: 04-07/2024 --> nächster Einsatz 08/2024

Danke!
