### ISSUE TITLE
Menü ausblenden

### ISSUE THREAD

**Issue by dennisd93** [abrain/einsatzverwaltung#296]
Hallo,

kann mir jemand sagen, wie man das Menü in den Einsatzberichten ausblenden kann? 
![Screenshot 2024-04-01 201612](https://github.com/abrain/einsatzverwaltung/assets/165412759/15142b87-ffe7-4a09-95e4-1311d3277547)

Danke!

Gruß
Dennis

**Comment by abrain** [comment]
Das ist ein Teil des Themes und müsste dort umgebaut werden.

Als unschönen Hack könnte man das auch per CSS ausblenden, aber die Frage ist, ob die Überschrift dann noch an anderer Stelle auftaucht?

Zum Theme-Umbau helfen vielleicht folgende Links:
- https://einsatzverwaltung.org/2016/08/individuelle-anpassungen-vornehmen/
- https://developer.wordpress.org/themes/advanced-topics/child-themes/
