### ISSUE TITLE
Fixe Spaltenbreite bestimmen 

### ISSUE THREAD

**Issue by Frankiii1984** [abrain/einsatzverwaltung#305]
Hi,

wir haben bei unserer Einsatzliste das Problem, dass Datum und Uhrzeit nicht vollständig in einer Zeile abgebildet werden, da die Spalte zu klein ist. Kann ich irgendwie eine feste Spaltenbreite vorgeben?

Damit ihr euch ein Bild machen könnt, hier der Link:
https://feuerwehr.sinzig.de/einsatze

**Comment by abrain** [comment]
Danke für den Hinweis, das sollte nicht so sein. 

Per CSS lässt es sich hiermit lösen:

```
.einsatz-column-date, .einsatz-column-time {
	white-space: nowrap;
}
```

Das kommt dann auch in Kürze mit einem Update mit.
