### ISSUE TITLE
Einsätze werden erst ab 01.01.1995 angezeigt

### ISSUE THREAD

**Issue by Schmakus** [abrain/einsatzverwaltung#307]
Hallo,
Einsätze mit Datum vor 01.01.1995 werden in der Einsatzübersicht nicht angezeigt und im Wordpress-Archiv werden nur die Jahreszahlen ohne Titel angezeigt.

[http://www.ffw-mutlangen.de/einsatzuebersicht/](http://www.ffw-mutlangen.de/einsatzuebersicht/)

**Comment by abrain** [comment]
Ich habe den Effekt jetzt auf http://www.ffw-mutlangen.de/einsatzuebersicht/einsaetze-archiv/ gesehen.

Werden die fraglichen/fehlenden Jahre mit dem Shortcode `[einsatzjahre]` angezeigt?

**Comment by Schmakus** [comment]
Hi, habe den Fehler gefunden!
Ich hatte den shortcode `[einsatzliste jahr=-30 monatetrennen=ja sort=ab]`. Durch das minus 30 wurden die früheren Einsätze nicht angezeigt. Jedoch ganz das `jahr`weglassen geht auch nicht. nun habe ich `jahr=-200`.

`[einsatzjahre]` funktioniert auch. Ideal wäre ne Option, um auf ne Textmarke zu springen, anstatt auch ne Archivseite.

**Comment by abrain** [comment]
Ah ok, das erklärt's.

> Jedoch ganz das `jahr`weglassen geht auch nicht. nun habe ich `jahr=-200`.

Mit `jahr=*` werden übrigens immer alle angezeigt, egal wie lange zurück.
