### ISSUE TITLE
CSV-Export von Einsatzberichten

### ISSUE THREAD

**Issue by abrain** [abrain/einsatzverwaltung#63]

**Comment by heikobornholdt** [comment]
Moin,

ich würden einen CSV-Export benötigen. Ich kann aus dem Issue hier nicht ersehen, ob du die Idee verworfen hast oder ob dieses Feature bereits eingebaut wurde.

Beste Grüße,
Heiko

**Comment by abrain** [comment]
Hi, es gab mal eine Zeit, da habe ich alle Issues in eine private JIRA-Instanz verschoben und die entsprechenden Issues hier geschlossen. Die Idee dahinter war, dass nicht alles ein wirklich geplantes Feature war, sondern erst mal Ideensammlung. Das hätte/hat die Liste der Issues unnötig lang gemacht.

Ich werde diesen Schritt aber nun wieder zurückrollen und die geschlossenen Issues wieder eröffnen, sobald sie gewünscht werden oder sonst wie für die Entwicklung in nächster Zeit in Frage kommen.

**Comment by heikobornholdt** [comment]
Sehr schön, so ist das transparenter für alle :) .

Soll ich mich um die Umsetzung des Features kümmern und dann einen MR erstellen oder willst du das Feature lieber selbst entwickeln?

**Comment by abrain** [comment]
> Sehr schön, so ist das transparenter für alle :) .

Ja, dachte ich mir dann auch ;)

Da ich erst noch die 1.3.1 vor mir und für die 1.4.0 schon andere Features im Auge habe, kannst du dich da gerne autoben. Im Hinblick auf die Erweiterbarkeit (z.B. #64 ) ist es sicher sinnvoll, auf allgemeine Interfaces und Wiederverwendbarkeit zu achten (vgl. Sources und Helper beim Import, wobei ich nicht behaupten mag, dass das alles ideal gelöst ist). So eine Verallgemeinerung kann aber auch in einem zweiten Schritt stattfinden, nachdem einmal klar ist, wie der Prozess läuft.

**Comment by heikobornholdt** [comment]
Alles klar. Ich habe mich mal an ein Mockup gesetzt.

Ich habe mich beim Aussehen an der "Daten exportieren"-Seite von WordPress und bei den Funktionen bei der "Export"-Seite von phpMyAdmin orientiert:
![einsatzverwaltung export mockup](https://cloud.githubusercontent.com/assets/789788/26608184/8a1059de-459a-11e7-99be-98e2cd2f7d0a.gif)

Was sagst du dazu?

**Comment by heikobornholdt** [comment]
Sobald du mir Rückmeldung zum Mockup gegeben hast, würde ich mich an die Implementierung setzen 😁 .

**Comment by abrain** [comment]
Gefällt mir gut. Bei den Optionen für CSV bin ich mir unschlüssig, ob die Auswahl des Escape-Zeichens nicht schon zu krass ist. Oder eben klarer kennzeichnen, welche Einstellungen essentiell sind und von welchen man besser die Finger lässt, wenn man nicht weiß, was es ist. Entsprechend sind dann vernünftige Standardwerte wichtig.

Ist JSON hier nur beispielhaft aufgeführt oder würdest du das gleich mitmachen?

**Comment by heikobornholdt** [comment]
Bei der Option für das Escape-Zeichen habe ich ganz ähnlich gedacht, jedoch würde das Weglassen dieser Option auch die anderen beiden Optionen einschränken, da man nicht mehr frei die Zeichen wählen könnte. Ich denke solange wir da vernünftige Standardwerte nehmen, sollte das Niemanden verwirren.

JSON wollte ich direkt mitmachen. Dann sehe ich direkt, ob ich ein brauchbares Interface für das Export-Format gewählt habe.
