### ISSUE TITLE
Trennzeichen in Einsatznummer

### ISSUE THREAD

**Issue by abrain** [abrain/einsatzverwaltung#65]
Es sollen Trennzeichen wie z. B. ein Bindestrich in der Einsatznummer möglich sein.

**Comment by wurzelserver** [comment]
Gibts zufällig einen Zeitplan für die Umsetzung?

**Comment by abrain** [comment]
Hi, einen Zeitplan nicht, aber ich arbeite gerade wieder an einem neuen Release.

Was würdest du dir konkret anders wünschen? Die Auswahl der Trennzeichen wird erst mal begrenzt sein, aber derzeit denke ich an Bindestrich und Schrägstrich.

**Comment by wurzelserver** [comment]
Hi, Bindestrich wäre klasse. Wir trennen die Einsätze immer im Format Einsatznummer-Jahr. Das würde ich gerne so abbilden.
