### ISSUE TITLE
Permalinks / Ansicht der Einsätze

### ISSUE THREAD

**Issue by sebastianroming** [abrain/einsatzverwaltung#85]
Per Definition ist der Permalink auf "einsaetze" gesetzt. Wenn nun aber in Wordpress bereits eine Seite mit dem Permalink "einsaetze" angelegt ist, kann auf dieser Seite die Einsatzliste nicht angezeigt werden.
Es wäre wünschenswert, den Permalink "einsaetze" frei verwenden zu können, sowie die Permalinkstruktur einzelner Beiträge (Einsatzberichte) frei zu definieren (z.B. foobar.com/einsaetze/2015/TITEL).

**Comment by abrain** [comment]
Den Permalinkbasis festzusetzen ist tatsächlich ein bisschen unschön. Das mit der Permalinkstruktur für die einzelnen Beiträge muss ich mir näher ansehen, wenn das derzeitige Konzept der Einsatznummern ohnehin auf den Prüfstand kommt.

**Comment by sebastianroming** [comment]
Ich bin bisher auf noch keine umsetzbare Lösung gestoßen. Sollte ich aber was finden, starte ich mal n pull request...

**Comment by duxtalparum** [comment]
Ich habe eher durch Zufall ein workaround für dieses Problem gefunden. Bei mir war es auch so, dass ich eine Seite "einsaetze" erstellt hatte und dort die Einsatzliste darstellen wollte. Alle Einsätze wurden dort dann als "Post" dargestellt. Um zu prüfen ob es an irgendwelchen Seiteneinstellungen liegt, habe ich eine neue Seite erstellt und diese erstmal "Test" genannt. Dort wurde die Einsatzliste ohne Probleme in tabellarischer Form dargestellt. Dann habe ich die Seite in Einsätze umbenannt und diese hat nun den permalink "einsaetze-2" bekommen und die alte (zuerst erstellte) Seite "Einsätze" ist im Papierkorb gelandet.

**Comment by abrain** [comment]
Ich habe das gerade mal bei mir nachgestellt und es scheint so, als ob WordPress der neuen Seite tatsächlich den Permalink "einsaetze" zuweist, obwohl der eigentlich vom Archiv (Auflistung als Posts) belegt ist.
Als Workaround kann man entweder etwas eigenes wie "unsere-einsaetze" vergeben, oder (so ist es bei meiner Feuerwehr) die Seite einer anderen Seite unterstellen, z.B. /aktive-wehr/einsaetze/.
Aber ja, diese Probleme gäbe es nicht, wenn man Permalinkbasis einstellen könnte. Machbar ist das durchaus, ich schaue mal, wie schnell ich das hinbekomme.

**Comment by sebastianroming** [comment]
Gibt es schon ein Releaseplan für die 1.0.0? ;)

**Comment by abrain** [comment]
Leider nein :disappointed:

**Comment by abrain** [comment]
Mit dem Commit von eben würde ich diesen Issue schließen und alles weitere in #94 behandeln?

**Comment by sebastianroming** [comment]
Einwandfrei - vielen Dank!
