### ISSUE TITLE
Jahrestabelle Smartphone kompatibel (Tabelle passt sich nicht der Displaygröße an)

### ISSUE THREAD

**Issue by forvert112** [abrain/einsatzverwaltung#87]

**Comment by Brunsben** [comment]
Über eine Lösung für dieses Problem würde ich mich freuen, aktuell zerschießt die Tabelle mein Mobile-Theme!

**Comment by abrain** [comment]
Erster Anlauf umgesetzt in 05aa5d907c8e87aa8895361ddd38ad6aa7eb80b0
