### ISSUE TITLE
Einsatznummer im Widget auswählbar

### ISSUE THREAD

**Issue by duxtalparum** [abrain/einsatzverwaltung#88]
Es wäre schön, wenn man im Widget auch die Einsatznummer anzeigen lassen könnte.

Vielen Dank auf diesem Wege für Deine Arbeit!!!

**Comment by abrain** [comment]
Ist notiert, danke :)

**Comment by abrain** [comment]
Es wird ein zusätzliches neues Widget geben, dessen Inhalt man komplett selbst gestalten kann, inkl. Einsatznummer versteht sich.
