### ISSUE TITLE
Templates/Themes für Einsatzberichte

### ISSUE THREAD

**Issue by sebastianroming** [abrain/einsatzverwaltung#89]
Wünschenswert wäre eine anpassbare Darstellung für Einsatzberichte (sowohl Liste als auch Einzeldarstellung).
Eventuell als template files, die bei einem Plugin-Update nicht automatisch überschrieben werden.

**Comment by abrain** [comment]
Die Liste ist derzeit schon in Überarbeitung für Version 0.9 (zumindest die Reihenfolge der Spalten und es kommen weitere Spalten dazu), das Layout der einzelnen Einsatzberichte kommt dann mit der 1.0

**Comment by sebastianroming** [comment]
Die Listendarstellung lässt sich nun ja super anpassen. Danke dafür.
Jetzt wäre noch die Darstellung der einzelnen Einsätze wünschenswert: wir benötigen z.B. keine Alarmzeit und auch das Alarmstichwort sollte nur für interne Zwecke verwendet werden, nicht aber auf der Webseite dargestellt werden.

**Comment by abrain** [comment]
Ja, nach den Listen sind jetzt die einzelnen Berichte dran. Ich hatte vor, das ähnlich aufzuziehen wie mit den Spalten, dass man die einzelnen Angaben per Drag & Drop verteilen kann, wie man will.

**Comment by sebastianroming** [comment]
Konnte die Funktion leider nicht in der neuen 1.0 finden - bin ich zu blöd? ;-)

**Comment by abrain** [comment]
Ähm, ne, da kann ich dich beruhigen ;) Das Feature hat's leider doch nicht in die 1.0 geschafft :disappointed: Es waren einfach einige andere Features schon fertig herumgelegen und ich wollte das releasen.
