### ISSUE TITLE
Hinweis auf Bilder

### ISSUE THREAD

**Issue by duxtalparum** [abrain/einsatzverwaltung#90]
Es wäre noch schön, wenn man auswählen könnte, dass zu einem Einsatz eine Bildergalerie existiert. Dies könnte dann in der Einsatzübersichtsliste mit einem kleinen Icon symbolisiert werden.

Vielen Dank.

**Comment by abrain** [comment]
Ja, das kann ich mir gut vorstellen. Der Einfachheit halber würde ich schauen, ob ein Beitragsbild gesetzt ist und daran erkennen, ob Bilder vorhanden sind, oder nicht. Ansonsten müsste der Beitragstext nach Bildern und Galerien durchsucht werden.

**Comment by duxtalparum** [comment]
Grundsätzlich kann man es über ein Beitragsbild machen. Jedoch würde dies zu Problemen führen, wenn jemand immer einsatzstichwortabhängig ein Symbolbild als Beitragsbild einfügen würde. Ich könnte mir auch vorstellen, dass der Punkt "Bildergalerie" einfach über einen Haken in jedem Einsatzbericht manuell gesetzt werden könnte und dann entsprechend ein Symbol in der Übersicht bei diesem Einsatz angezeigt wird. Ich bin mir noch nicht ganz sicher welches die bessere Variante ist :-).

**Comment by VPatrick** [comment]
Ich würde einen Haken beim Erstellen eines Einsatzberichts ganz gut finden.
