### ISSUE TITLE
Hauptuser hat keinen Zugriff auf Einsatzberichte

### ISSUE THREAD

**Issue by mad-max** [abrain/einsatzverwaltung#92]
In der aktuellen Version können Einsatzberichte nur von Usern angelegt werden, die nicht der erstangelegte Benutzer sind. Unabhängig von der Rechteverwaltung sieht der Hauptuser die Einsatzverwaltung nicht auf der linken Seite des Adminpanel. Neu angelegte User haben dieses Problem nicht. Getestet auf Wordpress 4.1

**Comment by abrain** [comment]
Habe gerade zum Test ein WordPress 4.1.1 frisch aufgesetzt und Einsatzverwaltung 0.8.4 installiert und kann mit dem ersten und einzigen User den Menüpunkt sehen und auch einen Einsatzbericht anlegen. In der Mail (sorry, dass ich bisher nicht geantwortet hatte) steht, dass es ebenfalls eine Neuinstallation war? (Vor einer Woche habe ich von einem Fall gehört, der nach einem Update von einer Version < 0.7 ausging.)
Um den Fehler etwas einzugrenzen hätte ich noch ein paar Fragen:
* Welche Rolle hat der Hauptuser, der den Menüpunkt nicht sieht?
* Welche Rollen haben die anderen User, bei denen es geht?
* Bleiben auf der Einstellungsseite die Häkchen bei der Rechteverwaltung nach dem Speichern für alle Rollen erhalten?
* Besteht Zugriff auf die Datenbank (z.B. phpMyAdmin), um ein paar Werte direkt nachsehen zu können?

**Comment by abrain** [comment]
Hallo, kannst du das bitte nochmal mit der eben erschienenen Version 0.9.0 versuchen? Einstellungen neu speichern sollte auf jeden Fall helfen.

**Comment by abrain** [comment]
Keine Reaktion, auch nicht per Mail. Nachdem keine weiteren Meldungen über solch ein Verhalten des Plugins eingegangen sind, schließe ich den Issue.

**Comment by abrain** [comment]
Vermutlich behoben mit #100
