### ISSUE TITLE
Eingesetzte Fahrzeuge kategorisieren

### ISSUE THREAD

**Issue by sebastianroming** [abrain/einsatzverwaltung#93]
Wünschenswert wäre eine Funktion zur Kategorisierung einzelner Fahrzeuge, z.B. nach Abteilungen, die dann auch strukturiert dargestellt werden.

**Comment by abrain** [comment]
Das ist eine Eigenschaft eines Fahrzeugs, die auch immer gleich und nicht von Einsatz zu Einsatz verschieden ist, oder?

**Comment by sebastianroming** [comment]
Ja genau - meines Erachtens nach ist das eine generelle
Einstellung/Kategorisierung der Fahrzeuge, also über die Fahrzeuge
realisierbar.

**Comment by sebastianroming** [comment]
@abrain Kurze Frage: wird das Plugin noch weiterentwickelt? Seit 3 Monaten kein commit mehr... :(

**Comment by abrain** [comment]
Zumindest seit 3 Monaten kein Release mehr, Commits gabs in den letzten Tagen ein paar, allerdings im develop-Branch ;)
Bei mir ist gereade Prüfungswoche und am Wochenende hat unsere Feuerwehr 140-jähriges Jubiläum. Ich komme derzeit nicht ernsthaft zu was. Es geht aber nächste Woche, spätestens Mitte August weiter.

**Comment by abrain** [comment]
@sebastianroming Mein Lösungsansatz wäre die Fahrzeuge auch zu einer hierarchischen Taxonomie (vgl. Einsatzart, Kategorie, ...) zu machen. Das würde bedeuten, dass ein Fahrzeug max. zu einer z.B. Abteilung gehören kann. Gäbe es da Einwände?

**Comment by sebastianroming** [comment]
Das ist ja auch völlig korrekt so. Jedes Fahrzeug hat exakt EINEN festen Standort.

**Comment by abrain** [comment]
Behoben mit ba7842856b57f1ca3275f158467c8c6575d222a3
