### ISSUE TITLE
Permalinks: Einsatztitel statt Einsatznummer

### ISSUE THREAD

**Issue by sebastianroming** [abrain/einsatzverwaltung#94]
Es wäre wünschenswert, wenn es eine Auswahl zwischen "Einsatztitel" oder "Einsatznummer" als Permalink gäbe. Wir bevorzugen den Titel - auch aus SEO-Gründen.

**Comment by sebastianroming** [comment]
Dies sollte für bereits angelegte Einsätze auch nachträglich änderbar sein.
Momentan ist dies leider nicht möglich.

**Comment by sebastianroming** [comment]
Wäre z.B. relativ einfach realisierbar:

```
$slug = sanitize_title($_POST['post_title']);
if(!empty($slug)) {
    $update_args['post_name'] = $slug;
}
```

**Comment by abrain** [comment]
Den Titel zu verwenden ist bei WordPress ohnehin der Standard, da müsste man nur die Sonderbehandlung von 'post_name' weglassen. Allerdings ergibt sich dann früher oder später das Problem, wenn z.B. mehrere Einsätze den gleichen Titel haben, die später eingegebenen zusätzlich eine Nummmer angehängt bekommen, um Eindeutigkeit zu gewährleisten.
So wie ich mir die Lösung für #85 momentan vorstelle, kannst du dir dann die URL sowieso selbst zusammenbauen. Persönlich fände ich dann /einsatzberichte/{Einsatznummer für die Eindeutigkeit}/{Einsatztitel für SEO aber eigentlich ist egal was hier steht} eine gute Variante.

**Comment by sebastianroming** [comment]
Das wäre meiner Meinung nach sogar die Beste Lösung. 
Jetzt muss die Funktion nur noch integriert werden :)

**Comment by abrain** [comment]
Die URLs nutzen mit 7e988c7a1c9d6e816a085f410dc3f5db5bc64744 den Beitragstitel als Slug, wie normale WordPress-Beiträge auch.
