### ISSUE TITLE
Bestimmte Einsätze besonders hervorheben

### ISSUE THREAD

**Issue by sebastianroming** [abrain/einsatzverwaltung#96]
Es wäre wünschenswert, bestimmte Einsätze besonders "hervorzuheben", um diese gesondert auf einer Seite "Besondere Einsätze" darzustellen (vgl. hierzu http://dunningen112.de/c/einsaetze/besondere-einsaetze).

**Comment by sebastianroming** [comment]
Gibt´s schon eine Roadmap für meine offenen issues? :-)

**Comment by abrain** [comment]
Ich habe mit den besonderen Einsätzen gerade leider noch ein Datenbankproblem, das ich erst noch lösen muss. Deshalb ist das aus dem heutigen Update mal ausgeklammert.

**Comment by sebastianroming** [comment]
@abrain Kein Problem - solange ich weiß, dass es kommen wird, bin ich schon glücklich ;-)
