### ISSUE TITLE
Nur die letzten 10 Einsätze anzeigen

### ISSUE THREAD

**Issue by DrWeizen** [abrain/einsatzverwaltung#97]
Hallo,
wenn ich z.Bsp. auf der Startseite das Plugin einfügen möchte und nur die letzten 10 Einsätze darstellen will, wie kann ich dies machen? Leider habe ich keinen Shortcode dazu gefunden.

Danke und Gruess
Andy

**Comment by abrain** [comment]
Das wäre eigentlich schon ein Fall für [einsatzliste], dieser Shortcode hat aber im Moment keinen Paramter, um die Anzahl der gezeigten Einsätze zu begrenzen. Das nehme ich mal als Verbesserungsvorschlag auf, danke!

**Comment by abrain** [comment]
Alternativ steht natürlich das Widget zur Verfügung, aber mit 10 Einsätzen ist das wohl nicht mehr so praktikabel.

**Comment by DrWeizen** [comment]
gerne. Das mit der Anzahl von 10 Einsätzen war auch nur ein Beispiel, als Erklärung, wir haben eine Page für die Einsätze wo alle angezeigt werden, aber auf der Startseite möchte ich ja nicht alle sondern nur die letzten 10 oder 5 Einsätze oder cool wäre auch nur die vom aktuellen monat.
