### ISSUE TITLE
Spaltenbreite bei monatetrennen=ja

### ISSUE THREAD

**Issue by Brunsben** [abrain/einsatzverwaltung#99]
Wenn man als Parameter "monatetrennen=ja" angibt, dann werden pro Monat die Spaltenbreiten getrennt berechnet. 
Das sieht doch sehr eigen aus. 
Es wäre schön wenn man die alle auf die gleiche Breite bekommen könnte.

**Comment by abrain** [comment]
Richtig, das ist ein öfters bemängelter Zustand, den ich im nächsten kleinen Update 0.9.2 beheben möchte.
